export function getSeededDB() {
  return {
    "profiles": [
      {
        "id": "p1",
        "full_name": "أحمد المدير",
        "username": "admin",
        "role": "admin",
        "phone": "01011112222",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p2",
        "full_name": "عفاف أحمد",
        "username": "afaf",
        "role": "cleaner",
        "phone": "01234567890",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "16:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p3",
        "full_name": "رحاب محمود",
        "username": "rehab",
        "role": "cleaner",
        "phone": "01122334455",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "16:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p4",
        "full_name": "خالد المشرف",
        "username": "supervisor",
        "role": "supervisor",
        "phone": "01555666777",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      }
    ],
    "locations": [
      {
        "id": "l1",
        "name": "مقر النرجس الرئيسي",
        "address": "شارع التسعين الشمالي، التجمع الخامس، القاهرة"
      }
    ],
    "zones": [
      {
        "id": "z1",
        "location_id": "l1",
        "name": "منطقة الاستقبال والانتظار",
        "code": "SOP_REC01",
        "floor": "الأرضي",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
        "sort_order": 1
      },
      {
        "id": "z2",
        "location_id": "l1",
        "name": "مكاتب الموظفين ووحدات الأدراج",
        "code": "SOP_OFF01",
        "floor": "الأول",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=600",
        "sort_order": 2
      },
      {
        "id": "z3",
        "location_id": "l1",
        "name": "دورات المياه (حمام الإدارة والحمامين العلويين)",
        "code": "SOP_WSH01",
        "floor": "الأرضي والأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
        "sort_order": 3
      },
      {
        "id": "z4",
        "location_id": "l1",
        "name": "المختبر والمعرض (Material Lab / VR / Built-In)",
        "code": "SOP_LAB01",
        "floor": "الأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600",
        "sort_order": 4
      },
      {
        "id": "z5",
        "location_id": "l1",
        "name": "الواجهات والزجاج والسلم",
        "code": "SOP_GLS01",
        "floor": "الداخلي والخارجي",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400",
        "sort_order": 5
      }
    ],
    "task_templates": [
      {
        "id": "t1_afaf",
        "zone_id": "z2",
        "task_code": "SOP_WALL_01",
        "title": "تنظيف التجاليد الخشبية والحوائط (أ. عفاف - الإثنين)",
        "description": "تنظيف الحوائط والتجاليد الخشبية مرتين أسبوعياً (يوم الإثنين بالتناوب مع أ. رحاب) مع إزالة البصمات والأتربة.",
        "goal": "الحفاظ على المظهر الفاخر للتجاليد الخشبية والحوائط",
        "category": "نظافة",
        "tools_required": "ملمع خشب + فوطة ميكروفايبر",
        "frequency": "مرتين أسبوعياً",
        "recurrence_days": ["الاثنين"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "10:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t1_rehab",
        "zone_id": "z2",
        "task_code": "SOP_WALL_02",
        "title": "تنظيف التجاليد الخشبية والحوائط (أ. رحاب - الخميس)",
        "description": "تنظيف الحوائط والتجاليد الخشبية مرتين أسبوعياً (يوم الخميس بالتناوب مع أ. عفاف) مع إزالة البصمات والأتربة.",
        "goal": "الحفاظ على المظهر الفاخر للتجاليد الخشبية والحوائط بالتناوب",
        "category": "نظافة",
        "tools_required": "ملمع خشب + فوطة ميكروفايبر",
        "frequency": "مرتين أسبوعياً",
        "recurrence_days": ["الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "10:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t2_sat",
        "zone_id": "z5",
        "task_code": "SOP_GLASS_01",
        "title": "تنظيف الأبواب والشبابيك والزجاج (أ. عفاف - السبت)",
        "description": "تنظيف وتلميع الأبواب والزجاج والشبابيك والمرايات بالكامل 3 مرات أسبوعياً (يوم السبت).",
        "goal": "الحفاظ على لمعان ونظافة جميع الأسطح الزجاجية والأبواب",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + فوطة ميكروفايبر زرقاء",
        "frequency": "ثلاث مرات أسبوعياً",
        "recurrence_days": ["السبت"],
        "estimated_duration_minutes": 40,
        "scheduled_time": "11:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t2_mon_wed",
        "zone_id": "z5",
        "task_code": "SOP_GLASS_02",
        "title": "تنظيف الأبواب والشبابيك والزجاج (أ. رحاب - الإثنين والأربعاء)",
        "description": "تنظيف وتلميع الأبواب والزجاج والشبابيك والمرايات بالكامل 3 مرات أسبوعياً (أيام الإثنين والأربعاء).",
        "goal": "الحفاظ على لمعان ونظافة جميع الأسطح الزجاجية والأبواب",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + فوطة ميكروفايبر زرقاء",
        "frequency": "ثلاث مرات أسبوعياً",
        "recurrence_days": ["الاثنين", "الأربعاء"],
        "estimated_duration_minutes": 40,
        "scheduled_time": "11:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t3_g1",
        "zone_id": "z3",
        "task_code": "SOP_WSH_01",
        "title": "تفقد وتنظيف دورات المياه - الجولة الأولى (أ. عفاف)",
        "description": "تفقد حمام الإدارة والحمامين العلويين وتنظيفهما ومراجعة أي نواقص أو مستلزمات نظافة يومياً بدءاً من الساعة 9:00 صباحاً (الجولة الأولى).",
        "goal": "أعلى مستويات النظافة والتعقيم وتوافر المستلزمات بالحمامات",
        "category": "نظافة",
        "tools_required": "مطهرات ديتول وكلور + صابون ومناديل + مساحة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "09:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": true,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t3_g2",
        "zone_id": "z3",
        "task_code": "SOP_WSH_02",
        "title": "تفقد وتنظيف دورات المياه - الجولة الثانية (أ. رحاب)",
        "description": "تفقد حمام الإدارة والحمامين العلويين وتنظيفهما ومراجعة النواقص (الجولة الثانية اليومية بواسطة أ. رحاب).",
        "goal": "الحفاظ على جودة ونظافة الحمامات طوال ساعات العمل",
        "category": "نظافة",
        "tools_required": "مطهرات ديتول وكلور + صابون ومناديل + مساحة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "13:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": true,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t3_g3",
        "zone_id": "z3",
        "task_code": "SOP_WSH_03",
        "title": "تفقد وتنظيف دورات المياه - الجولة الثالثة (أ. رحاب)",
        "description": "تفقد حمام الإدارة والحمامين العلويين وتنظيفهما ومراجعة النواقص (الجولة الثالثة والأخيرة اليومية بواسطة أ. رحاب).",
        "goal": "تسليم الحمامات معقمة ونظيفة تماماً في نهاية اليوم",
        "category": "نظافة",
        "tools_required": "مطهرات ديتول وكلور + صابون ومناديل + مساحة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "16:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": true,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t4_offices",
        "zone_id": "z2",
        "task_code": "SOP_OFF_01",
        "title": "تنظيف مكاتب الموظفين ووحدات الأدراج (أ. عفاف)",
        "description": "البدء بتنظيف مكاتب الموظفين ووحدات الأدراج يومياً بدءاً من الساعة 8:10 صباحاً وحتى الساعة 9:00 صباحاً كأولوية قصوى.",
        "goal": "تهيئة المكاتب نظيفة ومعقمة قبل بدء ساعات العمل الرسمية",
        "category": "نظافة",
        "tools_required": "بخاخ مطهر أسطح + ملمع خشب + أكياس نفايات سوداء",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 50,
        "scheduled_time": "08:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t5_daily_glass",
        "zone_id": "z5",
        "task_code": "SOP_GLS_DAILY",
        "title": "تنظيف زجاج السلم والمكاتب والواجهات يومياً",
        "description": "تنظيف زجاج السلم وزجاج المكاتب وزجاج الواجهات الداخلية والأبواب بصفة يومية ومستمرة لإزالة أي بصمات أو أتربة.",
        "goal": "المحافظة على لمعان وبريق الزجاج والواجهات طوال اليوم",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + فوط مايكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "09:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t6_windows",
        "zone_id": "z5",
        "task_code": "SOP_WIN_3W",
        "title": "تنظيف زجاج الشبابيك (أ. رحاب)",
        "description": "تنظيف زجاج الشبابيك ثلاث مرات أسبوعياً (أيام السبت والإثنين والأربعاء) مع تلميع الأطر المعدنية وإزالة الغبار.",
        "goal": "ضمان نظافة وخلو شبابيك المبنى من الغبار والأتربة المتراكمة",
        "category": "نظافة",
        "tools_required": "ملمع زجاج + فرشاة مجرى شبابيك + فوط زرقاء",
        "frequency": "ثلاث مرات أسبوعياً",
        "recurrence_days": ["السبت", "الاثنين", "الأربعاء"],
        "estimated_duration_minutes": 35,
        "scheduled_time": "11:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t7_screens",
        "zone_id": "z1",
        "task_code": "SOP_SCR_DAILY",
        "title": "تنظيف الشاشات برفق (أ. رحاب)",
        "description": "تنظيف الشاشات وأجهزة العرض برفق شديد يومياً من الساعة 8:00 مساءً وحتى 9:00 مساءً باستخدام فوط وملمعات مخصصة.",
        "goal": "المحافظة على نظافة الشاشات الحساسة بدون تعريضها للخدش أو الضرر",
        "category": "نظافة",
        "tools_required": "ملمع شاشات خاص + فوطة ميكروفايبر ناعمة وجافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "20:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": false,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": false,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t8_ventilation",
        "zone_id": "z2",
        "task_code": "SOP_VENT_DAILY",
        "title": "تهوية وفتح الشبابيك يومياً (أ. عفاف)",
        "description": "فتح الشبابيك لتهوية وتجديد الهواء بالكامل في مكاتب الموظفين يومياً من الساعة 8:00 صباحاً وحتى 9:00 صباحاً قبل وصول الموظفين.",
        "goal": "تجديد هواء المكاتب وضمان بيئة صحية نشطة للموظفين",
        "category": "تشغيل",
        "tools_required": "مفتاح تأمين الشبابيك",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 60,
        "scheduled_time": "08:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": false,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": false,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t9_lab_areas",
        "zone_id": "z4",
        "task_code": "SOP_LAB_CLEAN",
        "title": "تنظيف مناطق Material Lab / VR / Built-In (أ. رحاب)",
        "description": "تنظيف وتعقيم الأسطح والأرضيات والأجهزة بمناطق المختبر وتجربة الواقع الافتراضي ومحطة البناء بدءاً من الساعة 2:00 ظهراً.",
        "goal": "ضمان جاهزية ونظافة أحدث المعامل والمعدات التقنية بالمقر",
        "category": "نظافة",
        "tools_required": "مناديل مبللة للعدسات والأجهزة + ملمع أسطح + مكنسة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 45,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t10_inner_facade",
        "zone_id": "z5",
        "task_code": "SOP_FAC_INNER",
        "title": "تنظيف الواجهات الداخلية (أ. عفاف)",
        "description": "تلميع ومسح الواجهات والأبواب الزجاجية الداخلية ومحيط السلم بدءاً من الساعة 12:00 ظهراً.",
        "goal": "المحافظة على لمعان وخلو الواجهات الداخلية من أي غبار أو بصمات",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + مساحة زجاج طويلة + فوطة ميكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "12:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t10_outer_facade",
        "zone_id": "z5",
        "task_code": "SOP_FAC_OUTER",
        "title": "تنظيف الواجهات الخارجية (أ. رحاب)",
        "description": "غسيل وتلميع زجاج الواجهات الخارجية للمبنى والمدخل الرئيسي بدءاً من الساعة 4:00 عصراً.",
        "goal": "ظهور المبنى والواجهة الرئيسية بمظهر جذاب ولامع للعامة والزوار",
        "category": "نظافة",
        "tools_required": "خرطوم مياه + مساحة زجاج تليسكوبية + ملمع خارجي",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 45,
        "scheduled_time": "16:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      }
    ],
    "task_instances": [
      {
        "id": "ti_hist1",
        "template_id": "t4_offices",
        "zone_id": "z2",
        "assigned_to": "p2",
        "assigned_by": "p1",
        "task_type": "recurring",
        "title": "تنظيف مكاتب الموظفين ووحدات الأدراج (أ. عفاف)",
        "description": "البدء بتنظيف مكاتب الموظفين ووحدات الأدراج يومياً بدءاً من الساعة 8:10 صباحاً وحتى الساعة 9:00 صباحاً كأولوية قصوى.",
        "due_date": "2026-07-11",
        "due_time": "08:10",
        "status": "completed",
        "photo_before_url": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400",
        "photo_after_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=400",
        "photo_after_taken_at": "2026-07-11T08:45:00Z",
        "employee_notes": "تم الانتهاء بالكامل من تنظيف وتلميع جميع مكاتب الموظفين بالكامل.",
        "supervisor_approved": true,
        "supervisor_approved_by": "p4",
        "supervisor_approved_at": "2026-07-11T08:50:00Z",
        "supervisor_notes": "عمل رائع وممتاز كالعادة ومكتمل قبل الموعد المحدد.",
        "quality_grade": "A",
        "started_at": "2026-07-11T08:10:00Z",
        "completed_at": "2026-07-11T08:45:00Z",
        "delay_minutes": 0,
        "created_at": "2026-07-11T00:00:00Z"
      },
      {
        "id": "ti_hist2",
        "template_id": "t3_g1",
        "zone_id": "z3",
        "assigned_to": "p2",
        "assigned_by": "p1",
        "task_type": "recurring",
        "title": "تفقد وتنظيف دورات المياه - الجولة الأولى (أ. عفاف)",
        "description": "تفقد حمام الإدارة والحمامين العلويين وتنظيفهما ومراجعة أي نواقص أو مستلزمات نظافة يومياً بدءاً من الساعة 9:00 صباحاً (الجولة الأولى).",
        "due_date": "2026-07-11",
        "due_time": "09:00",
        "status": "completed",
        "photo_before_url": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=400",
        "photo_after_url": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=400",
        "photo_after_taken_at": "2026-07-11T09:20:00Z",
        "employee_notes": "تم التفتيش وإضافة صابون ومناشف ورقية جديدة.",
        "supervisor_approved": true,
        "supervisor_approved_by": "p4",
        "supervisor_approved_at": "2026-07-11T09:25:00Z",
        "supervisor_notes": "الحمامات نظيفة جداً ومعقمة.",
        "quality_grade": "A",
        "started_at": "2026-07-11T09:00:00Z",
        "completed_at": "2026-07-11T09:20:00Z",
        "delay_minutes": 0,
        "created_at": "2026-07-11T00:00:00Z"
      },
      {
        "id": "ti_hist3",
        "template_id": "t9_lab_areas",
        "zone_id": "z4",
        "assigned_to": "p3",
        "assigned_by": "p1",
        "task_type": "recurring",
        "title": "تنظيف مناطق Material Lab / VR / Built-In (أ. رحاب)",
        "description": "تنظيف وتعقيم الأسطح والأرضيات والأجهزة بمناطق المختبر وتجربة الواقع الافتراضي ومحطة البناء بدءاً من الساعة 2:00 ظهراً.",
        "due_date": "2026-07-11",
        "due_time": "14:00",
        "status": "completed",
        "photo_before_url": "https://images.unsplash.com/photo-1517256064527-09c53b2d0c6b?auto=format&fit=crop&q=400",
        "photo_after_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=400",
        "photo_after_taken_at": "2026-07-11T14:35:00Z",
        "employee_notes": "تم تنظيف المعامل ومسح الغبار وتجهيز الشاشات.",
        "supervisor_approved": true,
        "supervisor_approved_by": "p4",
        "supervisor_approved_at": "2026-07-11T14:45:00Z",
        "quality_grade": "A",
        "started_at": "2026-07-11T14:00:00Z",
        "completed_at": "2026-07-11T14:35:00Z",
        "delay_minutes": 0,
        "created_at": "2026-07-11T00:00:00Z"
      }
    ],
    "operational_tasks": [
      {
        "id": "op_lights",
        "zone_id": "z1",
        "title": "تشغيل وتعديل وحدات الإضاءة يومياً",
        "description": "تشغيل الإضاءة الهادئة حتى 12 ظهراً، الإضاءة المتوسطة من 12 ظهراً لـ 5 مساءً، والإضاءة الكاملة من 5 مساءً لـ 10 مساءً.",
        "schedule_windows": [
          { "from": "08:00", "to": "12:00", "mode": "إضاءة هادئة 💡" },
          { "from": "12:00", "to": "17:00", "mode": "إضاءة متوسطة 🔆" },
          { "from": "17:00", "to": "22:00", "mode": "إضاءة كاملة ⚡" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SW_LIGHT_01", "SW_LIGHT_02"],
        "is_active": true
      },
      {
        "id": "op_ac",
        "zone_id": "z2",
        "title": "تشغيل وإطفاء التكييفات (موظفي النظافة فقط)",
        "description": "تشغيل التكييفات بدءاً من الساعة 9:00 صباحاً وإغلاقها بالكامل في تمام الساعة 10:00 مساءً من قبل موظفي النظافة فقط.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل وضبط الحرارة على 23 ❄️" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SW_AC_MAIN", "SW_AC_OFFICE"],
        "is_active": true
      },
      {
        "id": "op_sound",
        "zone_id": "z1",
        "title": "تشغيل الساوند سيستم يومياً",
        "description": "تشغيل نظام الصوت المركزي على الخلفية الموسيقية الهادئة من الساعة 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل مستمر هادئ 🎵" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SW_SOUND_01"],
        "is_active": true
      },
      {
        "id": "op_fountain",
        "zone_id": "z1",
        "title": "تشغيل وإطفاء النوافير والشلالات",
        "description": "تشغيل النوافير والشلالات وإطفاءها لإزالة الرواسب بصفة يومية مستمرة.",
        "schedule_windows": [
          { "from": "09:00", "to": "18:00", "mode": "تشغيل مستمر  Fountain ⛲" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SW_FOUNT_01"],
        "is_active": true
      },
      {
        "id": "op_screens",
        "zone_id": "z1",
        "title": "تشغيل شاشات العرض بالاستقبال",
        "description": "تشغيل شاشات العرض الترحيبية عند منطقة الاستقبال يومياً من 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "عرض ترحيبي ذكي 📺" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SW_SCREEN_01"],
        "is_active": true
      },
      {
        "id": "op_diffusers",
        "zone_id": "z1",
        "title": "تشغيل فواحات الهواء يومياً",
        "description": "تشغيل فواحات الهواء العطرية لنشر الروائح الزكية بالاستقبال من الساعة 9:00 صباحاً وحتى 9:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "21:00", "mode": "تعطير مستمر تلقائي 🌸" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SW_DIFF_01"],
        "is_active": true
      }
    ],
    "kpi_snapshots": [
      {
        "id": "k1",
        "profile_id": "p2",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 15,
        "tasks_completed_on_time": 14,
        "tasks_late": 1,
        "tasks_reworked": 0,
        "compliance_rate": 93.3,
        "avg_execution_time_minutes": 16.5,
        "quality_score": 95,
        "supervisor_rating": 4.8
      },
      {
        "id": "k2",
        "profile_id": "p3",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 18,
        "tasks_completed_on_time": 18,
        "tasks_late": 0,
        "tasks_reworked": 1,
        "compliance_rate": 100,
        "avg_execution_time_minutes": 23.2,
        "quality_score": 88,
        "supervisor_rating": 4.5
      }
    ],
    "notifications": [
      {
        "id": "n1",
        "recipient_id": "p2",
        "type": "task_assigned",
        "title": "مهمة جديدة مسندة إليك",
        "body": "تم تكليفك بمهمة تنظيف مكاتب الموظفين ووحدات الأدراج اليوم.",
        "related_task_instance_id": "",
        "is_read": false,
        "created_at": "2026-07-12T01:00:00Z"
      }
    ],
    "device_switches": [
      {
        "id": "sw1",
        "code": "SW_LIGHT_01",
        "label": "إضاءة الاستقبال الهادئة",
        "zone_id": "z1",
        "panel_location": "لوحة المدخل رقم 1"
      },
      {
        "id": "sw2",
        "code": "SW_AC_MAIN",
        "label": "مفتاح تكييف الاستقبال الرئيسي",
        "zone_id": "z1",
        "panel_location": "لوحة المدخل رقم 1"
      },
      {
        "id": "sw3",
        "code": "SW_FOUNT_01",
        "label": "مضخة مياه النافورة الوسطى",
        "zone_id": "z1",
        "panel_location": "لوحة التحكم الخارجية"
      },
      {
        "id": "sw4",
        "code": "SW_SCREEN_01",
        "label": "شاشة عرض الاستقبال الرئيسية",
        "zone_id": "z1",
        "panel_location": "خلف شاشة الاستقبال"
      }
    ]
  };
}
