export function getSeededDB() {
  const dbData = {
    "profiles": [
      {
        "id": "p1",
        "full_name": "أحمد المدير",
        "username": "admin",
        "role": "admin",
        "phone": "01011112222",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p2",
        "full_name": "عفاف أحمد",
        "username": "afaf",
        "role": "cleaner",
        "phone": "01234567890",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "16:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p3",
        "full_name": "رحاب محمود",
        "username": "rehab",
        "role": "cleaner",
        "phone": "01122334455",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "14:00",
        "shift_end": "22:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p4",
        "full_name": "خالد المشرف",
        "username": "supervisor",
        "role": "supervisor",
        "phone": "01555666777",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      }
    ],
    "locations": [
      {
        "id": "l1",
        "name": "مقر النرجس الرئيسي",
        "address": "شارع النرجس، التجمع الخامس، القاهرة"
      }
    ],
    "zones": [
      {
        "id": "z_facades",
        "location_id": "l1",
        "name": "الواجهات",
        "code": "SOP_REC01",
        "floor": "1",
        "responsible_employee_id": "p2",
        "cover_image_url": "",
        "sort_order": 1
      },
      {
        "id": "z_reception",
        "location_id": "l1",
        "name": "الاستقبال Reception",
        "code": "SOP_REC05",
        "floor": "1",
        "responsible_employee_id": "p2",
        "cover_image_url": "",
        "sort_order": 2
      },
      {
        "id": "z_team_office",
        "location_id": "l1",
        "name": "Team & Technical OFFICE",
        "code": "SOP_TOF11",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "",
        "sort_order": 3
      },
      {
        "id": "z_proxessory",
        "location_id": "l1",
        "name": "Proxessory Station",
        "code": "SOP_PXSC17",
        "floor": "بدروم",
        "responsible_employee_id": "p3",
        "cover_image_url": "",
        "sort_order": 4
      },
      {
        "id": "z_bathrooms",
        "location_id": "l1",
        "name": "دورات المياة الثلاثة",
        "code": "SOP_BR26",
        "floor": "1/ بدروم",
        "responsible_employee_id": "p3",
        "cover_image_url": "",
        "sort_order": 5
      },
      {
        "id": "z_material_lab",
        "location_id": "l1",
        "name": "Material Lab",
        "code": "SOP_MLB36",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "",
        "sort_order": 6
      },
      {
        "id": "z_vr_experience",
        "location_id": "l1",
        "name": "VR Experience",
        "code": "SOP_VRE41",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "",
        "sort_order": 7
      },
      {
        "id": "z_built_in",
        "location_id": "l1",
        "name": "Bult-IN Station",
        "code": "SOP_BIN47",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "",
        "sort_order": 8
      },
      {
        "id": "z_pro_home",
        "location_id": "l1",
        "name": "PRO HOME Station",
        "code": "SOP_BIN51",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "",
        "sort_order": 9
      },
      {
        "id": "z_warehouse",
        "location_id": "l1",
        "name": "المخزن",
        "code": "SOP_STC56",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "",
        "sort_order": 10
      }
    ],
    "task_templates": [
  {
    "id": "t_sop_01",
    "zone_id": "z_facades",
    "task_code": "SOP_FAC_01",
    "title": "تنظيف وتلميع الواجهة الداخلية والبوابات والسلالم",
    "description": "1. تنظيف البوابة الزجاجية\n2. تلميع وتنظيف البوابة الزجاج والمراية والسلالم",
    "goal": "تنظيف وتلميع الواجهة الداخلية والبوابات والسلالم",
    "category": "نظافة",
    "tools_required": "ملمع خشب وزجاج، فوطة مايكروفايبر",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 30,
    "scheduled_time": "12:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_02",
    "zone_id": "z_facades",
    "task_code": "SOP_FAC_02",
    "title": "تنظيف الواجهة الخارجية وأعمدة الإنارة وري الزرع",
    "description": "1. تنظيف أمام الشارع وأعمدة الإنارة وري الزرع\n2. تلميع وتنظيف البوابتين الحديد الخارجية",
    "goal": "تنظيف الواجهة الخارجية وأعمدة الإنارة وري الزرع",
    "category": "نظافة",
    "tools_required": "ملمع، فوطة مايكروفايبر، مكنسة، خرطوم مياه",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 45,
    "scheduled_time": "16:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_03",
    "zone_id": "z_facades",
    "task_code": "SOP_FAC_03",
    "title": "تنظيف وتلميع الزجاج والسلالم الداخلية",
    "description": "1. تنظيف زجاج السلم\n2. تنظيف السلم الأرضي الداخلي",
    "goal": "تنظيف وتلميع الزجاج والسلالم الداخلية",
    "category": "نظافة",
    "tools_required": "ملمع زجاج، فوطة مايكروفايبر",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 30,
    "scheduled_time": "08:30",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_04",
    "zone_id": "z_facades",
    "task_code": "SOP_FAC_04",
    "title": "تنظيف النافورة والزلط المحيط بها",
    "description": "1. تنظيف النافورة\n2. تنظيف الزلط",
    "goal": "تنظيف النافورة والزلط المحيط بها",
    "category": "نظافة",
    "tools_required": "ملمع، فوطة مايكروفايبر",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "08:20",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_05",
    "zone_id": "z_facades",
    "task_code": "SOP_FAC_05",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية\n2. تنظيف الحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 40,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_06",
    "zone_id": "z_reception",
    "task_code": "SOP_REC_01",
    "title": "تنظيف المكاتب والكراسي وترتيب أسطح المكاتب",
    "description": "1.  تنظيف المكاتب من الأتربة\n2. تنظيف الكراسي من أي مخلفات\n3. ترتيب سطح المكتب",
    "goal": "تنظيف المكاتب والكراسي وترتيب أسطح المكاتب",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، معطر",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "08:10",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_07",
    "zone_id": "z_reception",
    "task_code": "SOP_REC_02",
    "title": "تنظيف الشاشات بقطعة قماش مناسبة",
    "description": "1. مسح الشاشة بلطف\n2. تنظيف شاشات العمل",
    "goal": "تنظيف الشاشات بقطعة قماش مناسبة",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع شاشات",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 15,
    "scheduled_time": "20:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_08",
    "zone_id": "z_reception",
    "task_code": "SOP_REC_03",
    "title": "تنظيف الأرضيات وتبطين سلة المهملات",
    "description": "1. تنظيف ومسح الأرضيات\n2. تفريغ سلة المهملات",
    "goal": "تنظيف الأرضيات وتبطين سلة المهملات",
    "category": "نظافة",
    "tools_required": "مكنسة، جردل وممسحة",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "08:40",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_09",
    "zone_id": "z_reception",
    "task_code": "SOP_REC_04",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية\n2. تنظيف الحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب / زجاج",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 35,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_10",
    "zone_id": "z_team_office",
    "task_code": "SOP_TOF_01",
    "title": "تنظيف المكاتب والكراسي والأدراج وترتيبها",
    "description": "1. تنظيف سطح المكتب وترتيبه\n2. تنظيف الكراسي\n3. تنظيف وحدات الأدراج\n4. مسح وتنظيف الأدراج",
    "goal": "تنظيف المكاتب والكراسي والأدراج وترتيبها",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، معطر، ملمع خشب",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 35,
    "scheduled_time": "08:10",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_11",
    "zone_id": "z_team_office",
    "task_code": "SOP_TOF_02",
    "title": "تنظيف شاشات العمل",
    "description": "1. مسح وتنظيف شاشات العمل بقطعة قماش مناسبة",
    "goal": "تنظيف شاشات العمل",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع شاشات",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 15,
    "scheduled_time": "20:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_12",
    "zone_id": "z_team_office",
    "task_code": "SOP_TOF_03",
    "title": "تفريغ وتنظيف الأرضيات وسلة المهملات",
    "description": "1. تفريغ وتنظيف الأرضيات\n2. تفريغ سلة المهملات",
    "goal": "تفريغ وتنظيف الأرضيات وسلة المهملات",
    "category": "نظافة",
    "tools_required": "مكنسة، جردل وممسحة",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "08:40",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_13",
    "zone_id": "z_team_office",
    "task_code": "SOP_TOF_04",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1.  تنظيف وتلميع التجاليد الخشبية\n2. تنظيف الحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 40,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_14",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_01",
    "title": "تلميع وتنظيف جميع وحدات العرض والأجنحة والجزيرة الوسطية والأدراج",
    "description": "1. تلميع وتنظيف الجناح الأيمن\n2. تلميع وتنظيف جناح الوسط\n3. تلميع وتنظيف الجناح الأيسر\n4. تلميع وتنظيف الجزيرة الوسطية\n5. تلميع وتنظيف الأدراج الداخلية والخارجية",
    "goal": "تلميع وتنظيف جميع وحدات العرض والأجنحة والجزيرة الوسطية والأدراج",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 45,
    "scheduled_time": "14:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_15",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_02",
    "title": "ضمان أن الجزيرة الوسطية نظيفة عند عرض محتوياتها للعميل",
    "description": "تنظيف وتلميع الجزيرة الوسطية بالأدراج الداخلية والـ Just Top",
    "goal": "ضمان أن الجزيرة الوسطية نظيفة عند عرض محتوياتها للعميل",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 15,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_16",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_03",
    "title": "ضمان نظافة عرض المحطة على العملاء - الجناح الأيمن",
    "description": "تنظيف وتلميع الضلف الخارجية والداخلية والليد للجناح الأيمن",
    "goal": "ضمان نظافة عرض المحطة على العملاء",
    "category": "نظافة",
    "tools_required": "مكنسة، ممسحة، جردل",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_17",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_04",
    "title": "ضمان نظافة عرض المحطة على العملاء - الرخام والزجاج",
    "description": "تنظيف وتلميع الرخام والضلف الزجاجية والضلف والأرفف الداخلية",
    "goal": "ضمان نظافة عرض المحطة على العملاء",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_18",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_05",
    "title": "ضمان نظافة عرض المحطة على العملاء - الجناح الأيسر",
    "description": "تنظيف وتلميع الضلف الخارجية والداخلية والليد للجناح الأيسر",
    "goal": "ضمان نظافة عرض المحطة على العملاء",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع معادن",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_19",
    "zone_id": "z_proxessory",
    "task_code": "SOP_PXS_06",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية والحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب / زجاج",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 35,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_20_1",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_01_M",
    "title": "تنظيف باب الحمامات والحوض والمرايات (المرة الأولى صباحاً)",
    "description": "1. تنظيف باب الحمامات\n2. تنظيف الحوض من الرواسب والأتربة\n3. تنظيف المرايات",
    "goal": "تنظيف باب الحمامات والحوض والمرايات",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج وخشب، معطر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "09:00",
    "scheduled_times": ["09:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_20_2",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_01_A",
    "title": "تنظيف باب الحمامات والحوض والمرايات (المرة الثانية ظهراً)",
    "description": "1.  تنظيف باب الحمامات\n2. تنظيف الحوض من الرواسب والأتربة\n3. تنظيف المرايات",
    "goal": "تنظيف باب الحمامات والحوض والمرايات",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج وخشب، معطر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "13:00",
    "scheduled_times": ["13:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_20_3",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_01_E",
    "title": "تنظيف باب الحمامات والحوض والمرايات (المرة الثالثة مساءً)",
    "description": "1. تنظيف باب الحمامات\n2. تنظيف الحوض من الرواسب والأتربة\n3. تنظيف المرايات",
    "goal": "تنظيف باب الحمامات والحوض والمرايات",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج وخشب، معطر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "17:00",
    "scheduled_times": ["17:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_21_1",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_02_M",
    "title": "تنظيف المرحاض والبانيو والحوائط والسيراميك (المرة الأولى صباحاً)",
    "description": "1. تنظيف قاعدة المرحاض وغسلها\n2. تنظيف البانيو أو الشاور وغسله\n3. تنظيف الحوائط والسيراميك",
    "goal": "تنظيف المرحاض والبانيو والحوائط والسيراميك",
    "category": "نظافة",
    "tools_required": "سلكة حوض، ملمع، معطر، منظف مطهر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "09:00",
    "scheduled_times": ["09:00"],
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_21_2",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_02_A",
    "title": "تنظيف المرحاض والبانيو والحوائط والسيراميك (المرة الثانية ظهراً)",
    "description": "1. تنظيف قاعدة المرحاض وغسلها\n2. تنظيف البانيو أو الشاور وغسله\n3. تنظيف الحوائط والسيراميك",
    "goal": "تنظيف المرحاض والبانيو والحوائط والسيراميك",
    "category": "نظافة",
    "tools_required": "سلكة حوض، ملمع، معطر، منظف مطهر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "13:00",
    "scheduled_times": ["13:00"],
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_21_3",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_02_E",
    "title": "تنظيف المرحاض والبانيو والحوائط والسيراميك (المرة الثالثة مساءً)",
    "description": "1. تنظيف قاعدة المرحاض وغسلها\n2. تنظيف البانيو أو الشاور وغسله\n3. تنظيف الحوائط والسيراميك",
    "goal": "تنظيف المرحاض والبانيو والحوائط والسيراميك",
    "category": "نظافة",
    "tools_required": "سلكة حوض، ملمع، معطر، منظف مطهر",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "17:00",
    "scheduled_times": ["17:00"],
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_22_1",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_03_M",
    "title": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات (المرة الأولى صباحاً)",
    "description": "1. إزالة المخلفات من سلة المهملات\n2. تعبئة موزع الصابون ووضع مناديل\n3. وضع معطر جو داخل وحدات الحمام\n4.  تنظيف ومسح الأرضيات",
    "goal": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات",
    "category": "صيانة",
    "tools_required": "جردل وممسحة، معطر، مناديل ورقية، صابون",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "09:00",
    "scheduled_times": ["09:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_22_2",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_03_A",
    "title": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات (المرة الثانية ظهراً)",
    "description": "1. إزالة المخلفات من سلة المهملات\n2. تعبئة موزع الصابون ووضع مناديل\n3. وضع معطر جو داخل وحدات الحمام\n4. تنظيف ومسح الأرضيات",
    "goal": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات",
    "category": "صيانة",
    "tools_required": "جردل وممسحة، معطر، مناديل ورقية، صابون",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "13:00",
    "scheduled_times": ["13:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_22_3",
    "zone_id": "z_bathrooms",
    "task_code": "SOP_BR_03_E",
    "title": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات (المرة الثالثة مساءً)",
    "description": "1. إزالة المخلفات من سلة المهملات\n2. تعبئة موزع الصابون ووضع مناديل\n3. وضع معطر جو داخل وحدات الحمام\n4. تنظيف ومسح الأرضيات",
    "goal": "تفريغ المهملات وتعبئة المستلزمات ووضع المعطر وتنظيف الأرضيات",
    "category": "صيانة",
    "tools_required": "جردل وممسحة، معطر، مناديل ورقية، صابون",
    "frequency": "ثلاث مرات يوميا",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 20,
    "scheduled_time": "17:00",
    "scheduled_times": ["17:00"],
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_23",
    "zone_id": "z_material_lab",
    "task_code": "SOP_MLB_01",
    "title": "تنظيف وتلميع وترتيب العينات وتنظيف الأدراج والأرفف والأرضية",
    "description": "1. ترتيب وتنظيف العينات والتأكد من اكتمالها\n2. تنظيف الأسطح الخارجية وترتيب المحتويات (الأدراج)\n3. تنظيف الأرفف وترتيب العينات\n4. تنظيف الأرضية وإزالة الأتربة",
    "goal": "تنظيف وتلميع وترتيب العينات وتنظيف الأدراج والأرفف والأرضية",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 40,
    "scheduled_time": "14:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_24",
    "zone_id": "z_material_lab",
    "task_code": "SOP_MLB_02",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "الحفاظ على نظافة الحوائط الخشبية أثناء زيارة العميل للمعرض",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 30,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_25",
    "zone_id": "z_vr_experience",
    "task_code": "SOP_VRE_01",
    "title": "تنظيف VR Experience: الأرضية والشاشة والحوائط والتكييف والأرفف",
    "description": "1. تنظيف الأرضية وإزالة الأتربة والبقع\n2. تنظيف شاشة الـ LED\n3. إزالة الأتربة من الحوائط\n4. تنظيف الوحدة الخارجية للتكييف\n5. تنظيف الأرفف والأدراج",
    "goal": "تنظيف VR Experience: الأرضية والشاشة والحوائط والتكييف والأرفف",
    "category": "نظافة",
    "tools_required": "مكنسة، جردل وممسحة، فوطة مايكروفايبر، ملمع شاشات، ملمع زجاج",
    "frequency": "أسبوعي",
    "recurrence_days": [
      "الخميس"
    ],
    "estimated_duration_minutes": 50,
    "scheduled_time": "14:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_26",
    "zone_id": "z_vr_experience",
    "task_code": "SOP_VRE_02",
    "title": "تنظيف وتلميع الشباك",
    "description": "1. تنظيف وتلميع الشباك والزجاج",
    "goal": "تنظيف وتلميع الشباك",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج",
    "frequency": "ثلاث مرات أسبوعيا",
    "recurrence_days": [
      "السبت",
      "الاثنين",
      "الأربعاء"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_27",
    "zone_id": "z_vr_experience",
    "task_code": "SOP_VRE_03",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية والحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب / زجاج",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 30,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_28",
    "zone_id": "z_built_in",
    "task_code": "SOP_BIN_01",
    "title": "تنظيف Built-IN Station: وحدات العرض والأرفف وإضاءة LED والأرضية",
    "description": "1. تنظيف وحدات العرض من الداخل والخارج\n2. تنظيف الأرفف وإزالة الأتربة\n3. تنظيف وحدات إضاءة LED\n4. تنظيف الأرضية",
    "goal": "تنظيف Built-IN Station: وحدات العرض والأرفف وإضاءة LED والأرضية",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع شاشات، ملمع زجاج وخشب، مكنسة، ممسحة",
    "frequency": "أسبوعي",
    "recurrence_days": [
      "الخميس"
    ],
    "estimated_duration_minutes": 50,
    "scheduled_time": "14:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p3",
    "is_active": true
  },
  {
    "id": "t_sop_29",
    "zone_id": "z_built_in",
    "task_code": "SOP_BIN_02",
    "title": "تنظيف وتلميع الشباك",
    "description": "1. تنظيف وتلميع الشباك والزجاج",
    "goal": "تنظيف وتلميع الشباك",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج",
    "frequency": "ثلاث مرات أسبوعيا",
    "recurrence_days": [
      "السبت",
      "الاثنين",
      "الأربعاء"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_30",
    "zone_id": "z_built_in",
    "task_code": "SOP_BIN_03",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية والحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب / زجاج",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 35,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_31",
    "zone_id": "z_pro_home",
    "task_code": "SOP_PHS_01",
    "title": "تنظيف PRO HOME Station: أجهزة المكاتب والأرضيات والسلالم",
    "description": "1.  تنظيف الأسطح الخارجية لأجهزة ومكاتب الـ Call Center\n2. تنظيف الأرضية وإزالة الأتربة والبقع والمخلفات\n3. تنظيف درجات السلالم والجانبين",
    "goal": "تنظيف PRO HOME Station: أجهزة المكاتب والأرضيات والسلالم",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج وخشب، مكنسة، ممسحة، جردل",
    "frequency": "يومي",
    "recurrence_days": [
      "السبت",
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس"
    ],
    "estimated_duration_minutes": 40,
    "scheduled_time": "09:30",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": true,
    "default_assignee_id": "p2",
    "is_active": true
  },
  {
    "id": "t_sop_32",
    "zone_id": "z_pro_home",
    "task_code": "SOP_PHS_02",
    "title": "تنظيف وتلميع الشباك",
    "description": "1. تنظيف وتلميع الشباك والزجاج",
    "goal": "تنظيف وتلميع الشباك",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع زجاج",
    "frequency": "ثلاث مرات أسبوعيا",
    "recurrence_days": [
      "السبت",
      "الاثنين",
      "الأربعاء"
    ],
    "estimated_duration_minutes": 25,
    "scheduled_time": "14:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_33",
    "zone_id": "z_pro_home",
    "task_code": "SOP_PHS_03",
    "title": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "description": "1. تنظيف وتلميع التجاليد الخشبية والحوائط",
    "goal": "تنظيف وتلميع التجاليد الخشبية والحوائط",
    "category": "نظافة",
    "tools_required": "فوطة مايكروفايبر، ملمع خشب / زجاج",
    "frequency": "مرتين أسبوعيا",
    "recurrence_days": [
      "الأحد",
      "الثلاثاء"
    ],
    "estimated_duration_minutes": 35,
    "scheduled_time": "12:00",
    "requires_photo_before": false,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "",
    "is_active": true
  },
  {
    "id": "t_sop_34",
    "zone_id": "z_warehouse",
    "task_code": "SOP_WRH_01",
    "title": "تنظيف المخزن بالكامل: الأرضيات والأجهزة والترتيب والمهملات",
    "description": "1. تنظيف أرضية المخزن وإزالة الأتربة والمخلفات\n2. تنظيف الأسطح الخارجية للأجهزة\n3. إعادة ترتيب الأجهزة والكابلات في أماكنها\n4. تفريغ وتنظيف سلة المهملات",
    "goal": "تنظيف المخزن بالكامل: الأرضيات والأجهزة والترتيب والمهملات",
    "category": "نظافة",
    "tools_required": "مكنسة، ممسحة، جردل، فوطة مايكروفايبر، ملمع زجاج وخشب",
    "frequency": "أسبوعي",
    "recurrence_days": [
      "الخميس"
    ],
    "estimated_duration_minutes": 45,
    "scheduled_time": "17:00",
    "requires_photo_before": true,
    "requires_photo_after": true,
    "requires_supervisor_approval": true,
    "requires_gps": false,
    "requires_signature": false,
    "is_reopenable": true,
    "auto_escalate_if_late": false,
    "default_assignee_id": "p3",
    "is_active": true
  }
    ],
    "task_instances": [],
    "operational_tasks": [
      {
        "id": "op_lights",
        "zone_id": "z_reception",
        "title": "تشغيل وتعديل وحدات الإضاءة يومياً",
        "description": "تشغيل الإضاءة الهادئة حتى 12 ظهراً، الإضاءة المتوسطة من 12 ظهراً لـ 5 مساءً، والإضاءة الكاملة من 5 مساءً لـ 10 مساءً.",
        "schedule_windows": [
          { "from": "08:00", "to": "12:00", "mode": "إضاءة هادئة 💡" },
          { "from": "12:00", "to": "17:00", "mode": "إضاءة متوسطة 🔆" },
          { "from": "17:00", "to": "22:00", "mode": "إضاءة كاملة ⚡" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 001", "SWREC 002"],
        "is_active": true
      },
      {
        "id": "op_ac",
        "zone_id": "z_team_office",
        "title": "تشغيل وإطفاء التكييفات (موظفي النظافة فقط)",
        "description": "تشغيل التكييفات بدءاً من الساعة 9:00 صباحاً وإغلاقها بالكامل في تمام الساعة 10:00 مساءً من قبل موظفي النظافة فقط.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل وضبط الحرارة على 23 ❄️" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWBAS 015", "SWBAS 017"],
        "is_active": true
      },
      {
        "id": "op_sound",
        "zone_id": "z_reception",
        "title": "تشغيل الساوند سيستم يومياً",
        "description": "تشغيل نظام الصوت المركزي على الخلفية الموسيقية الهادئة من الساعة 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل مستمر هادئ 🎵" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 012"],
        "is_active": true
      },
      {
        "id": "op_fountain",
        "zone_id": "z_facades",
        "title": "تشغيل وإطفاء النوافير والشلالات",
        "description": "تشغيل النوافير والشلالات وإطفاءها لإزالة الرواسب بصفة يومية مستمرة.",
        "schedule_windows": [
          { "from": "09:00", "to": "18:00", "mode": "تشغيل مستمر Fountain ⛲" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 013"],
        "is_active": true
      },
      {
        "id": "op_screens",
        "zone_id": "z_reception",
        "title": "تشغيل شاشات العرض بالاستقبال",
        "description": "تشغيل شاشات العرض الترحيبية عند منطقة الاستقبال يومياً من 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "عرض ترحيبي ذكي 📺" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 009"],
        "is_active": true
      },
      {
        "id": "op_diffusers",
        "zone_id": "z_reception",
        "title": "تشغيل فواحات الهواء يومياً",
        "description": "تشغيل فواحات الهواء العطرية لنشر الروائح الزكية بالاستقبال من الساعة 9:00 صباحاً وحتى 9:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "21:00", "mode": "تعطير مستمر تلقائي 🌸" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 017"],
        "is_active": true
      }
    ],
    "kpi_snapshots": [
      {
        "id": "k1",
        "profile_id": "p2",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 25,
        "tasks_completed_on_time": 24,
        "tasks_late": 1,
        "tasks_reworked": 0,
        "compliance_rate": 96.0,
        "avg_execution_time_minutes": 18.5,
        "quality_score": 97,
        "supervisor_rating": 4.9
      },
      {
        "id": "k2",
        "profile_id": "p3",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 28,
        "tasks_completed_on_time": 28,
        "tasks_late": 0,
        "tasks_reworked": 1,
        "compliance_rate": 100,
        "avg_execution_time_minutes": 22.1,
        "quality_score": 94,
        "supervisor_rating": 4.7
      }
    ],
    "notifications": [],
    "device_switches": [
      // 1. لوحة الريسبشن والاستقبال (SWREC)
      { "id": "sw_rec_1", "code": "SWREC 001", "label": "إضاءات سقف مكاتب المهندسين", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_2", "code": "SWREC 002", "label": "ليد حائط حرف L", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_3", "code": "SWREC 003", "label": "ليد حائط وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_4", "code": "SWREC 004", "label": "ليد سقف وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_5", "code": "SWREC 005", "label": "ليد سقف", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_6", "code": "SWREC 006", "label": "اللمبة المدورة", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_7", "code": "SWREC 007", "label": "ليد السقف (7)", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_8", "code": "SWREC 008", "label": "ليد السقف (8)", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_9", "code": "SWREC 009", "label": "ليد أسود خلف مكاتب المهندسين", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_10", "code": "SWREC 010", "label": "ليد تجليدة مكتب وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_11", "code": "SWREC 011", "label": "إضاءة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_12", "code": "SWREC 012", "label": "ليد خلف كنبة استقبال عملاء", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_13", "code": "SWREC 013", "label": "ليد وش النافورة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_14", "code": "SWREC 014", "label": "إضاءة خارجية", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_15", "code": "SWREC 015", "label": "سبوتات (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_16", "code": "SWREC 016", "label": "لمبة سقف (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_17", "code": "SWREC 017", "label": "ليد زرع صناعي (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_18", "code": "SWREC 018", "label": "ليد مرايات (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_19", "code": "SWREC 019", "label": "إضاءة (خارجي - 19)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_20", "code": "SWREC 020", "label": "إضاءة (خارجي - 20)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_21", "code": "SWREC 021", "label": "سبوتات سوداء شمال (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_22", "code": "SWREC 022", "label": "لمبات الكور المضيئة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_23", "code": "SWREC 023", "label": "إضاءة رقم العمارة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_24", "code": "SWREC 024", "label": "سبوتات خارجية سوداء", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },

      // 2. لوحة عمال النظافة (SWMT)
      { "id": "sw_mt_1", "code": "SWMT 001", "label": "ليد سقف أعلى المفاتيح", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_2", "code": "SWMT 002", "label": "لمبات أعلى دخلة الحمام", "zone_id": "z_bathrooms", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_3", "code": "SWMT 003", "label": "ليد مكتبة الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_4", "code": "SWMT 004", "label": "ليد السقف لماتريال لاب (4)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_5", "code": "SWMT 005", "label": "ليد سقف ماتريال لاب (5)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_6", "code": "SWMT 006", "label": "ليد وسبوتات أعلى مكاتب مهندسين عند الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_7", "code": "SWMT 007", "label": "لمبات سقف مكان عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_8", "code": "SWMT 008", "label": "باقي لمبات سقف عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_9", "code": "SWMT 009", "label": "لمبات سقف السلم", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_10", "code": "SWMT 010", "label": "ليد أزرق VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_11", "code": "SWMT 011", "label": "ليد أحمر VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_12", "code": "SWMT 012", "label": "ليد التجاليد", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_13", "code": "SWMT 013", "label": "سبوت السلم الوسط", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_14", "code": "SWMT 014", "label": "ليد السلم العلوي", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_15", "code": "SWMT 015", "label": "ليد علوي مكتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_16", "code": "SWMT 016", "label": "سبوتات مكاتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_17", "code": "SWMT 017", "label": "Built-In Station سبوتات", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_18", "code": "SWMT 018", "label": "Built-In Station ليد سقف / ليد داخلي", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },

      // 3. لوحة Team Office & Technical (SWBAS)
      { "id": "sw_bas_1", "code": "SWBAS 001", "label": "ليد التجاليد خلف المكاتب", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_2", "code": "SWBAS 002", "label": "لمبات أعلى المكاتب (2)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_3", "code": "SWBAS 003", "label": "لمبات أعلى المكاتب (3)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_4", "code": "SWBAS 004", "label": "ليد التجاليد (4)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_5", "code": "SWBAS 005", "label": "ليد سقف أصفر", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_6", "code": "SWBAS 006", "label": "ليد سقف أبيض", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_7", "code": "SWBAS 007", "label": "ليد داخل بروكيسسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_8", "code": "SWBAS 008", "label": "لوجو بروكسيسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_9", "code": "SWBAS 009", "label": "ليد أصفر خلف الجزيرة", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_10", "code": "SWBAS 010", "label": "لمبات السقف أعلى الجزيرة (10)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_11", "code": "SWBAS 011", "label": "لمبات السقف أعلى الجزيرة (11)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_12", "code": "SWBAS 012", "label": "إضاءة بروكسيسوري (1)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_13", "code": "SWBAS 013", "label": "إضاءة بروكسيسوري (2)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_14", "code": "SWBAS 014", "label": "إضاءة بروكسيسوري (3)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_15", "code": "SWBAS 015", "label": "مفتاح التكييف الرئيسي", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" }
    ]
  };
  return dbData;
}