export function getSeededDB() {
  return {
    "profiles": [
      {
        "id": "p1",
        "full_name": "أحمد المدير",
        "username": "admin",
        "role": "admin",
        "phone": "01011112222",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p2",
        "full_name": "عفاف أحمد",
        "username": "afaf",
        "role": "cleaner",
        "phone": "01234567890",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "16:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p3",
        "full_name": "رحاب محمود",
        "username": "rehab",
        "role": "cleaner",
        "phone": "01122334455",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "14:00",
        "shift_end": "22:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p4",
        "full_name": "خالد المشرف",
        "username": "supervisor",
        "role": "supervisor",
        "phone": "01555666777",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      }
    ],
    "locations": [
      {
        "id": "l1",
        "name": "مقر النرجس الرئيسي",
        "address": "شارع النرجس، التجمع الخامس، القاهرة"
      }
    ],
    "zones": [
      {
        "id": "z_facades",
        "location_id": "l1",
        "name": "الواجهات",
        "code": "SOP_REC01",
        "floor": "1",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
        "sort_order": 1
      },
      {
        "id": "z_reception",
        "location_id": "l1",
        "name": "الاستقبال Reception",
        "code": "SOP_REC05",
        "floor": "1",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
        "sort_order": 2
      },
      {
        "id": "z_team_office",
        "location_id": "l1",
        "name": "Team & Technical OFFICE",
        "code": "SOP_TOF11",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=600",
        "sort_order": 3
      },
      {
        "id": "z_proxessory",
        "location_id": "l1",
        "name": "Proxessory Station",
        "code": "SOP_PXSC17",
        "floor": "بدروم",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
        "sort_order": 4
      },
      {
        "id": "z_bathrooms",
        "location_id": "l1",
        "name": "دورات المياة الثلاثة",
        "code": "SOP_BR26",
        "floor": "1/ بدروم",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
        "sort_order": 5
      },
      {
        "id": "z_material_lab",
        "location_id": "l1",
        "name": "Material Lab",
        "code": "SOP_MLB36",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600",
        "sort_order": 6
      },
      {
        "id": "z_vr_experience",
        "location_id": "l1",
        "name": "VR Experience",
        "code": "SOP_VRE41",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=600",
        "sort_order": 7
      },
      {
        "id": "z_built_in",
        "location_id": "l1",
        "name": "Bult-IN Station",
        "code": "SOP_BIN47",
        "floor": "1",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600",
        "sort_order": 8
      },
      {
        "id": "z_pro_home",
        "location_id": "l1",
        "name": "PRO HOME Station",
        "code": "SOP_BIN51",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1552581234-2612b753ee93?auto=format&fit=crop&q=80&w=600",
        "sort_order": 9
      },
      {
        "id": "z_warehouse",
        "location_id": "l1",
        "name": "المخزن",
        "code": "SOP_STC56",
        "floor": "بدروم",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=600",
        "sort_order": 10
      }
    ],
    "task_templates": [
      // 1. الواجهات (4 مهام)
      {
        "id": "t_sop_cle01",
        "zone_id": "z_facades",
        "task_code": "SOP_CLE01",
        "title": "الواجهة الخارجية (أمام الشارع - أعمدة إنارة - بوابة حديد - الزرع)",
        "description": "تنظيف أمام الشارع وأعمدة الإنارة وري الزرع والحفاظ على نظافة واجهة المقر الخارجية.",
        "goal": "الحفاظ على نظافة واجهة المقر الخارجية وجاهزيتها التامة لاستقبال العملاء.",
        "category": "نظافة",
        "tools_required": "ملمع - فوطة مايكرو فايبر - مكنسة - خرطوم مياه",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 60,
        "scheduled_time": "16:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle02",
        "zone_id": "z_facades",
        "task_code": "SOP_CLE02",
        "title": "الواجهة الداخلية والمدخل الرئيسي",
        "description": "تنظيف وتلميع البوابتين الحديد والزجاج والمراية والسلالم بشكل دوري.",
        "goal": "الحفاظ على نظافة واجهة المقر الداخلية والمداخل الزجاجية والرخام.",
        "category": "نظافة",
        "tools_required": "ملمع خشب وزجاج - فوطة مايكرو فايبر - مكنسة - خرطوم مياه",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "12:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle03",
        "zone_id": "z_facades",
        "task_code": "SOP_CLE03",
        "title": "تنظيف النافورة والزلط وتفريغ الفلاتر",
        "description": "تنظيف النافورة وإزالة الرواسب وتنسيق الزلط وتطهيرها لضمان نقاء المياه والمنظر الجمالي.",
        "goal": "الحفاظ على نظافة واجهة المقر الداخلية والنافورة بشكل دائم.",
        "category": "نظافة",
        "tools_required": "كلور ومطهر - سلة تفريغ - فوطة مايكرو فايبر - مكنسة",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين"],
        "estimated_duration_minutes": 120,
        "scheduled_time": "10:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle04",
        "zone_id": "z_facades",
        "task_code": "SOP_CLE04",
        "title": "تنظيف وتلميع التجاليد الخشبية للواجهة",
        "description": "تلميع وإزالة الأتربة من التجاليد الخشبية للواجهة باستخدام ملمع الخشب المخصص.",
        "goal": "الحفاظ على نظافة التجاليد الخشبية ومنع تراكم الغبار عليها.",
        "category": "نظافة",
        "tools_required": "ملمع خشب - فوطة مايكروفايبر ناعمة",
        "frequency": "أسبوعي",
        "recurrence_days": ["الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "11:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },

      // 2. الاستقبال Reception (6 مهام)
      {
        "id": "t_sop_cle05",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE05",
        "title": "مكاتب المهندسين بالاستقبال",
        "description": "تنظيف مكاتب المهندسين من الأتربة وترتيب الأسطح وتلميع الزجاج الخشبي.",
        "goal": "الحفاظ على مكان عمل المهندسين واستقبال العملاء في أبهى صورة.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - معطر - ملمع أسطح",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "08:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle06",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE06",
        "title": "كراسي الاستقبال وصالة الانتظار",
        "description": "تنظيف الكراسي الجلدية والقماشية من أي مخلفات وتعقيمها ومسح القواعد المعدنية.",
        "goal": "الحفاظ على جودة ونظافة المقاعد المعدة للزوار والمهندسين.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - معطر - مطهر مخفف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "08:20",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle07",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE07",
        "title": "شاشات عرض الاستقبال والمهندسين",
        "description": "مسح الشاشات بلطف بقطعة مايكروفايبر مع ملمع الشاشات الخاص لتفادي الخدوش.",
        "goal": "ضمان نقاء الرؤية وإزالة البصمات والأتربة من الشاشات الإلكترونية.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع شاشات خاص",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "08:25",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle08",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE08",
        "title": "الأرضيات الرخامية بالكامل ومطهر الانتظار",
        "description": "كنس ومسح أرضية صالة الاستقبال الرخامية بالكامل وتلميع زجاج المدخل ومطهر منطقة الانتظار.",
        "goal": "الحفاظ على المظهر الرخامي اللامع والراقي لصالة الاستقبال والانتظار.",
        "category": "نظافة",
        "tools_required": "مكنسة - جردل وممسحة - مطهر ومعطر أرضيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "08:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle09",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE09",
        "title": "التجاليد الخشبية والحوائط (الاستقبال)",
        "description": "تنظيف وتلميع التجاليد الخشبية وإزالة الغبار والبصمات من على الجدران الديكورية.",
        "goal": "المحافظة على المظهر الجمالي للأخشاب الفاخرة بالاستقبال.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب ممتاز",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 60,
        "scheduled_time": "10:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle10",
        "zone_id": "z_reception",
        "task_code": "SOP_CLE10",
        "title": "الشبابيك والزجاج الخارجي والداخلي (الاستقبال)",
        "description": "تنظيف وتلميع زجاج الشبابيك وإطاراتها الألومنيوم لإعطاء لمعان تام ونفاذ ممتاز للضوء.",
        "goal": "الحفاظ على نظافة زجاج النوافذ كجزء من الهوية البصرية.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج فعال - مساحة زجاج",
        "frequency": "أسبوعي",
        "recurrence_days": ["السبت", "الاثنين", "الأربعاء"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "11:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },

      // 3. Team & Technical OFFICE (6 مهام)
      {
        "id": "t_sop_cle11",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE11",
        "title": "مكاتب الموظفين وترتيبها (Team Office)",
        "description": "تنظيف أسطح مكاتب الموظفين من الأتربة وترتيب الأوراق وإعادة تنظيم الأغراض المتناثرة.",
        "goal": "توفير بيئة عمل نظيفة ومنظمة تعزز الإنتاجية للموظفين والتقنيين.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - معطر - رذاذ تنظيف معقم",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "08:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle12",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE12",
        "title": "كراسي العمل للموظفين (Team Office)",
        "description": "مسح الكراسي المكتبية من الغبار والاتساخات مع تعقيم المقاعد ومسح قواعد العجلات والظهر.",
        "goal": "المحافظة على نظافة وصحة كراسي المكاتب المخصصة للعمل الطويل.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - معقم أسطح - معطر لطيف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "08:40",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle13",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE13",
        "title": "تنظيف شاشات العمل للموظفين",
        "description": "تلميع ومسح شاشات الحواسيب للمهندسين والموظفين بلطف تام باستخدام ملمع شاشات وقطع قماش ناعمة جداً.",
        "goal": "تأمين شاشات نظيفة وخالية من البقع والغبار لراحة موظفي العمل التقني.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر مخصصة للشاشات - ملمع شاشات خاص",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "08:55",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle14",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE14",
        "title": "أرضيات وسلات المهملات (Team Office)",
        "description": "تفريغ سلات المهملات بالكامل وكنس ومسح الأرضيات وتطهيرها لضمان خلوها من الأتربة.",
        "goal": "الحفاظ على نظافة البيئة المحيطة وصحة المكاتب.",
        "category": "نظافة",
        "tools_required": "مكنسة - ممسحة مبللة - معقم أرضيات - أكياس قمامة جديدة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "09:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle15",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE15",
        "title": "وحدات الأدراج والملفات الخشبية",
        "description": "تلميع ومسح الأجزاء الخارجية لوحدات الأدراج والمقابض المعدنية ووحدات تنظيم الملفات.",
        "goal": "الحفاظ على رونق الأثاث المكتبي وتنظيمه.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب ممتاز",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "09:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle16",
        "zone_id": "z_team_office",
        "task_code": "SOP_CLE16",
        "title": "تلميع التجاليد الخشبية والحوائط (Team Office)",
        "description": "إزالة الأتربة والبصمات من على التجاليد الخشبية الفاخرة والحوائط المحيطة بمكاتب العمل.",
        "goal": "المحافظة على جودة ولمعان الديكورات الخشبية.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب مخصص",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 60,
        "scheduled_time": "10:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },

      // 4. Proxessory Station (9 مهام)
      {
        "id": "t_sop_cle17",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE17",
        "title": "الجناح الأيمن (Proxessory Station)",
        "description": "تنظيف وتلميع الضلف الخارجية والداخلية والتجاليد الخشبية والليد للجناح الأيمن المخصص لعرض المطبخ والملابس.",
        "goal": "تقديم عرض باهر للعملاء وخالٍ من الأتربة أو البصمات في الجناح الأيمن.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب عالي الجودة - ريشة غبار",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 60,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle18",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE18",
        "title": "جناح الوسط والرخام (Proxessory)",
        "description": "تلميع الرخام وتنظيف الأدراج والضلف الداخلية والتأكد من ترتيب محتويات الجناح الأوسط بالكامل.",
        "goal": "الحفاظ على لمعان الأسطح الرخامية في الواجهات الوسطية.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع رخام - ملمع أخشاب",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "15:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle19",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE19",
        "title": "الجناح الأيسر والتجاليد الخارجية (Proxessory)",
        "description": "تنظيف وتلميع الضلف والواجهات الخارجية والتجاليد الخشبية للجناح الأيسر لضمان مظهر موحد.",
        "goal": "المحافظة على جودة ونظافة مظهر الجناح الأيسر بالكامل.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب - فرشاة تنظيف الأركان",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "15:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle20",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE20",
        "title": "الجزيرة الوسطية والضلف الداخلية (Proxessory)",
        "description": "تنظيف وتلميع الأدراج والضلف والجزيرة الوسطية بشكل دائم ومسح الغبار من الداخل والخارج.",
        "goal": "ضمان أن الجزيرة التفاعلية بالوسط جاهزة للمس ومطالعة العينات الفاخرة.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب ممتاز",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "16:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle21",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE21",
        "title": "واجهات الزجاج والليد (Proxessory)",
        "description": "تلميع الواجهات الزجاجية بدقة عالية ومسح مسارات إضاءة الـ LED من الأتربة بلطف تام.",
        "goal": "المحافظة على صفاء ونظافة الزجاج الفاصل والرفوف الزجاجية بمحطة بروكيسسوري.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج مخصص ومضاد للبصمات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "16:20",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle22",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE22",
        "title": "أرضيات Proxessory Station",
        "description": "كنس ومسح الأرضية بالكامل وإزالة الأتربة والبقع الصعبة للحفاظ على مظهر متألق دائماً.",
        "goal": "توفير أرضية نظيفة تتماشى مع الطابع الراقي للمعرض الرئيسي.",
        "category": "نظافة",
        "tools_required": "مكنسة ناعمة - جردل وممسحة - مطهر ومعطر أرضيات قوي",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "16:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle23",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE23",
        "title": "باب الفيلا ومقابضه المعدنية",
        "description": "تنظيف وتلميع باب الفيلا الخشبي والزجاج من الجانبين مع تلميع المقابض والمفصلات المعدنية بالمنظف المخصص.",
        "goal": "الحفاظ على نظافة المدخل الأثري وباب الفيلا ومظهره الأنيق.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب - ملمع معادن مخصص للمقابض",
        "frequency": "أسبوعي",
        "recurrence_days": ["السبت", "الاثنين", "الأربعاء"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "17:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle24",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE24",
        "title": "التجاليد الخشبية والحوائط (Proxessory)",
        "description": "تنظيف وتلميع التجاليد الخشبية المحيطة وإزالة خيوط العنكبوت أو الغبار من الأركان المرتفعة.",
        "goal": "المحافظة على التجاليد الخشبية الجانبية وتفادي تراكم الغبار والأوساخ.",
        "category": "نظافة",
        "tools_required": "فرشاة سقف مرنة - فوطة مايكروفايبر - ملمع أخشاب",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "17:15",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle25",
        "zone_id": "z_proxessory",
        "task_code": "SOP_CLE25",
        "title": "JUST TOP (الجزيرة الوسطية)",
        "description": "تلميع السطح والقطع المعدنية الخاصة بوحدات JUST TOP وتطهيرها.",
        "goal": "الحفاظ على لمعان الأجزاء المعدنية والأسطح الملساء.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع معادن خاص",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "17:45",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },

      // 5. دورات المياة الثلاثة (10 مهام)
      {
        "id": "t_sop_cle26",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE26",
        "title": "أبواب الحمامات الثلاثة ومقابضها",
        "description": "تلميع الأبواب الخشبية وتعقيم المقابض المعدنية لحمام الإدارة والحمامين العلويين لمنع انتقال الجراثيم.",
        "goal": "تأمين أبواب حمامات نظيفة ومعقمة وخالية من البقع والبصمات.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - بخاخ معقم كحولي - ملمع خشب",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "09:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle27",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE27",
        "title": "أحواض الغسيل والصنبور والمحابس",
        "description": "تنظيف الحوض من الرواسب والتكلسات المائية وتلميع الصنبور والأجزاء المعدنية مع التعقيم بالكلور.",
        "goal": "توفير حوض صحي، نظيف وخالٍ تماماً من تراكم المياه والرواسب المزعجة.",
        "category": "نظافة",
        "tools_required": "سلكة إسفنجية - مطهر كلوركس - ملمع ستانلس مخصص",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "10:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle28",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE28",
        "title": "مرايا الحمامات وتلميعها",
        "description": "تلميع المرايا الموجودة في جميع الحمامات وإزالة رذاذ الماء وتراكم البصمات لتظهر بوضوح تام.",
        "goal": "ضمان مرايا نظيفة جداً وخالية من أي ضباب أو بقع.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر مخصصة للزجاج - ملمع زجاج",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "11:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle29",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE29",
        "title": "تعقيم قاعدة المرحاض وغسلها",
        "description": "غسل وتعقيم قاعدة الحمام بالكامل بالمنظف والمطهر المخصص مع تعقيم الغطاء والرافع الحديدي والرخامة الخلفية.",
        "goal": "توفير قاعدة مرحاض معقمة كلياً وخالية من الروائح والجراثيم.",
        "category": "نظافة",
        "tools_required": "فرشاة حمام - مطهر ديتول أو كلور - إسفنجة مخصصة للقاعدة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "12:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle30",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE30",
        "title": "البانيو أو منطقة الشاور",
        "description": "غسيل وتلميع البانيو أو كابينة الشاور الزجاجية بالكامل وإزالة بقع الصابون والتكلسات المائية والتجفيف لضمان رونقها.",
        "goal": "الحفاظ على لمعان وجفاف منطقة الاستحمام الملحقة بالحمامات.",
        "category": "نظافة",
        "tools_required": "منظف حمامات - سلكة ناعمة - مساحة ماء صغيرة للزجاج",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "13:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle31",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE31",
        "title": "الحوائط والسيراميك والواصلات",
        "description": "مسح وتلميع حوائط السيراميك وتطهير المفصلات والمحابس الجانبية من الرواسب والتكلسات لتبدو ناصعة.",
        "goal": "الحفاظ على لمعان ونظافة الجدران السيراميكية في الحمامات.",
        "category": "نظافة",
        "tools_required": "إسفنجة ناعمة - مطهر مخصص للسيراميك - فوطة تجفيف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "14:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle32",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE32",
        "title": "تفريغ سلات المهملات وتطهيرها",
        "description": "تفريغ سلات القمامة في كافة الحمامات وتعقيم السلة داخلياً ووضع أكياس قمامة معطرة وجديدة.",
        "goal": "منع تراكم النفايات وتجنب الروائح الكريهة نهائياً.",
        "category": "نظافة",
        "tools_required": "أكياس قمامة جديدة - بخاخ معقم برائحة الليمون",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "15:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle33",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE33",
        "title": "تعبئة موزعات الصابون والمناديل",
        "description": "تعبئة مستمرة لموزعات الصابون السائل وتوريد رولات المناديل الورقية ومتابعة النواقص في كافة الحمامات.",
        "goal": "توفير كافة مستلزمات النظافة باستمرار لراحة الموظفين والزوار.",
        "category": "نظافة",
        "tools_required": "صابون سائل معطر - مناديل رول فاخرة - كحول تعقيم",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "16:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle34",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE34",
        "title": "أرضيات الحمامات وتعقيمها بالكامل",
        "description": "مسح وتطهير أرضية السيراميك بالحمامات باستخدام مطهر ديتول المركز لضمان اللمعان التام والخلو من الأتربة والمياه.",
        "goal": "أرضيات حمام معقمة ونظيفة تماماً وجافة.",
        "category": "نظافة",
        "tools_required": "جردل وعصا ممسحة - مطهر أرضيات ديتول أو كلور",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "17:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle35",
        "zone_id": "z_bathrooms",
        "task_code": "SOP_CLE35",
        "title": "تنشيط وتعطير معطر الجو التلقائي",
        "description": "التأكد من عمل جهاز معطر الجو التلقائي وتنشيط الرائحة الزكية بالحمامات بشكل مستمر.",
        "goal": "المحافظة على رائحة عطرة تليق بمستوى حمامات المقر.",
        "category": "نظافة",
        "tools_required": "علب عبوة معطر جو جديدة وماتريكس التشغيل",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 5,
        "scheduled_time": "18:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },

      // 6. Material Lab (5 مهام)
      {
        "id": "t_sop_cle36",
        "zone_id": "z_material_lab",
        "task_code": "SOP_CLE36",
        "title": "تلميع التجاليد الخشبية والحوائط (Material Lab)",
        "description": "تنظيف وتلميع التجاليد الخشبية والحوائط الجانبية وتفقد مسارات الليد لإعطاء منظر فاخر خالي من الغبار.",
        "goal": "المحافظة على نظافة الديكورات الراقية بمعمل المواد.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب ممتاز",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle37",
        "zone_id": "z_material_lab",
        "task_code": "SOP_CLE37",
        "title": "ترتيب وتنظيف عينات المنتجات والأرفف",
        "description": "إزالة الأتربة من عينات الأخشاب والمعادن والأقمشة وترتيب العينات بشكل منظم وجذاب ومطابقتها للتصنيف المعتمد.",
        "goal": "المحافظة على معمل العينات نظيفاً جداً وجاهزاً لاستعراض العملاء الفوري.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب لطيف - ريشة غبار",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "14:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle38",
        "zone_id": "z_material_lab",
        "task_code": "SOP_CLE38",
        "title": "فتح الأدراج وتنظيفها من الداخل وتلميعها",
        "description": "فتح الأدراج الخشبية وسحب الملفات بلطف ومسح الأتربة الداخلية وتلميع المقابض وإعادة ترتيب العينات الداخلية بدقة.",
        "goal": "ضمان بقاء أدراج العينات نظيفة وخالية من نشارة الخشب أو الأتربة المتراكمة بالداخل.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب فعال - فرشاة شفط صغيرة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "15:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle39",
        "zone_id": "z_material_lab",
        "task_code": "SOP_CLE39",
        "title": "تلميع الأرفف والشبابيك والتكييف",
        "description": "تنظيف الأسطح الخارجية لمكيف الهواء ومسح زجاج النوافذ وإطاراتها بدقة مع تنظيف الأرفف المكشوفة.",
        "goal": "المحافظة على نظافة المحيط الخارجي وأجهزة التهوية بمعمل العينات.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج وخشب",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "15:20",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle40",
        "zone_id": "z_material_lab",
        "task_code": "SOP_CLE40",
        "title": "تنظيف أرضية معمل العينات وتطهيرها",
        "description": "كنس الأرضية وإزالة العينات الساقطة أو بقايا الأخشاب والرخام ومسحها بالكلور والمطهر المركز.",
        "goal": "أرضية معمل عينات خالية من الشوائب والأتربة.",
        "category": "نظافة",
        "tools_required": "مكنسة - جردل وممسحة - مطهر ومعطر أرضيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },

      // 7. VR Experience (6 مهام)
      {
        "id": "t_sop_cle41",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE41",
        "title": "تلميع جدران وتجاليد منطقة VR",
        "description": "تنظيف وتلميع التجاليد الديكورية الخشبية والأسطح المعتمة والحوائط لإزالة الغبار والبصمات.",
        "goal": "المحافظة على بيئة معتمة وراقية تليق بتجربة الواقع الافتراضي.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع أسطح وخشب فاخر",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle42",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE42",
        "title": "تلميع شاشة الـ LED العملاقة وأجهزة التحكم",
        "description": "تنظيف وتلميع الشاشة الكبيرة بقطعة قماش ناعمة جداً مع الملمع المخصص، وتعقيم نظارات الـ VR وأجهزة التحكم بدقة بالغة.",
        "goal": "ضمان أجهزة ونظارات معقمة وشاشة نظيفة خالية تماماً من البصمات لتجربة عملاء رائعة.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر للشاشات - ملمع شاشات خاص - كحول تعقيم مخصص للإلكترونيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "14:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle43",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE43",
        "title": "أرضية منطقة الـ VR وتعقيمها",
        "description": "تفريغ سلة المهملات وكنس ومسح الأرضية المظلمة للتخلص من أي غبار يعكر صفو الحركة الفنية.",
        "goal": "الحفاظ على أرضية آمنة ومعقمة لحركة العملاء المرتدين لنظارات الواقع الافتراضي.",
        "category": "نظافة",
        "tools_required": "مكنسة ناعمة - جردل وممسحة - مطهر ومعطر ذكي",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle44",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE44",
        "title": "تنظيف الأرفف والأدراج الخاصة بنظارات الـ VR",
        "description": "تلميع الأسطح الخارجية والداخلية لوحدات تنظيم الأجهزة، ومسح الأتربة وترتيب الشواحن والوصلات بدقة.",
        "goal": "توفير مكان تخزين مرتب وأنيق للإلكترونيات الحساسة.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج وأسطح",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:15",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle45",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE45",
        "title": "شباك وتكييف منطقة VR",
        "description": "تنظيف وتلميع الشباك الزجاجي الجانبي وإطاره ومسح الفلاتر الخارجية لوحدات التكييف من الأتربة.",
        "goal": "ضمان نظافة النوافذ وكفاءة تبريد التكييف في هذه المنطقة التقنية المتميزة.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج - ريشة غبار طويلة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle46",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_CLE46",
        "title": "إضاءة ليد وتعديل اللمبات الديكورية (VR)",
        "description": "تلميع شرائط الليد ومسح لمبات الديكور الدائري والجانبي بلطف لإضاءة ناصعة تليق بالعرض الرقمي.",
        "goal": "الحفاظ على المظهر الجمالي المضيء لوحدات الواقع الافتراضي.",
        "category": "نظافة",
        "tools_required": "فوطة جافة ناعمة جداً - أداة إزالة الغبار الساكن",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "15:45",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },

      // 8. Bult-IN Station (4 مهام)
      {
        "id": "t_sop_cle47",
        "zone_id": "z_built_in",
        "task_code": "SOP_CLE47",
        "title": "تنظيف وحدات عرض وأجهزة Built-In",
        "description": "تنظيف وحدات عرض Built-In الخشبية والزجاجية من الداخل والخارج وإزالة الأتربة والبقع الصعبة وتلميع التجاليد الخشبية.",
        "goal": "المحافظة على نظافة وجاهزية وحدات العرض المدمجة بشكل فاخر وجذاب.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب - ملمع شاشات للأجزاء اللامعة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle48",
        "zone_id": "z_built_in",
        "task_code": "SOP_CLE48",
        "title": "أرفف وأسطح محطة Built-In",
        "description": "تلميع الأرفف وإزالة الأتربة والغبار عن كافة العينات التابعة للشركاء والمعروضات المختلفة.",
        "goal": "الحفاظ على مظهر مرتب للوحدات وتلافي أي تراكم للغبار.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج وخشب",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle49",
        "zone_id": "z_built_in",
        "task_code": "SOP_CLE49",
        "title": "تنظيف لمبات LED للوحدات المدمجة",
        "description": "مسح وتلميع شريط إضاءة الليد المحيط بالوحدة واللمبات المعلقة بلطف تام لمنع تراكم الأتربة الكثيفة.",
        "goal": "المحافظة على كفاءة وقوة الإضاءة الموجهة نحو المعروضات.",
        "category": "نظافة",
        "tools_required": "فوطة جافة ناعمة جداً - ريشة غبار ناعمة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:45",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },
      {
        "id": "t_sop_cle50",
        "zone_id": "z_built_in",
        "task_code": "SOP_CLE50",
        "title": "أرضية Built-In ومحيط حمام السيدات",
        "description": "تطهير الأرضية بالكامل وكنس الأوساخ ومسح البقع بجوار حمام السيدات والممر الرئيسي الموازي.",
        "goal": "ضمان بقاء محيط الممر نظيفاً جداً ومعقماً.",
        "category": "نظافة",
        "tools_required": "مكنسة - ممسحة - جردل - مطهر أرضيات ديتول",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true
      },

      // 9. PRO HOME Station (5 مهام)
      {
        "id": "t_sop_cle51",
        "zone_id": "z_pro_home",
        "task_code": "SOP_CLE51",
        "title": "مكاتب وأجهزة الـ Call Center (Pro Home)",
        "description": "تنظيف الأسطح الخارجية لشاشات ولوحات مفاتيح الكول سنتر ومسح الغبار عن التجاليد الخشبية خلف المكاتب.",
        "goal": "المحافظة على بيئة مكاتب اتصالات نظيفة تعزز راحة الموظفين.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - رذاذ تعقيم لطيف - ملمع خشب وزجاج",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "08:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle52",
        "zone_id": "z_pro_home",
        "task_code": "SOP_CLE52",
        "title": "أرضية صالة Pro Home وعينات الديكور",
        "description": "تفريغ سلات المهملات وكنس ومسح أرضية صالة عرض برو هوم والتأكد من تطهيرها وصحة الرائحة بالداخل.",
        "goal": "ضمان صالة نظيفة لاستقبال عملاء ومطوري أنظمة المنازل الذكية.",
        "category": "نظافة",
        "tools_required": "مكنسة - ممسحة - جردل - معطر جو ومطهر أرضيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "09:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle53",
        "zone_id": "z_pro_home",
        "task_code": "SOP_CLE53",
        "title": "سلالم ومحيط صالة Pro Home",
        "description": "تنظيف السلالم المؤدية للبدروم والجانبين والزجاج الموازي لإزالة أي أوساخ أو بصمات وتجفيف السلم جيداً.",
        "goal": "توفير درج نظيف وآمن يضمن سلامة وصحة الزوار.",
        "category": "نظافة",
        "tools_required": "مكنسة - ممسحة مبللة بمطهر السيراميك - فوطة تجفيف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "09:30",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle54",
        "zone_id": "z_pro_home",
        "task_code": "SOP_CLE54",
        "title": "تلميع تجاليد وجدران محطة Pro Home",
        "description": "إزالة الأتربة والبصمات من على الأخشاب والتجاليد الجانبية المحيطة بـ Pro Home وصالة عرضها.",
        "goal": "الحفاظ على المظهر الفني الأنيق للشركة وصالة الـ Pro Home.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع خشب ممتاز - منفضة غبار ريشية",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "10:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle55",
        "zone_id": "z_pro_home",
        "task_code": "SOP_CLE55",
        "title": "شبابيك صالة Pro Home وإطاراتها المعدنية",
        "description": "تنظيف وتلميع زجاج النوافذ الألومنيوم الجانبية ومسح الغبار من مسارات الإطارات كلياً.",
        "goal": "ضمان زجاج نظيف ناصع للشبابيك المحيطة بالبدروم.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر - ملمع زجاج فعال - أداة تنظيف مسارات الشبابيك",
        "frequency": "أسبوعي",
        "recurrence_days": ["السبت", "الاثنين", "الأربعاء"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "10:45",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },

      // 10. المخزن (4 مهام)
      {
        "id": "t_sop_cle56",
        "zone_id": "z_warehouse",
        "task_code": "SOP_CLE56",
        "title": "أرضية المخزن وإزالة الأوساخ والمخلفات",
        "description": "كنس ومسح أرضية المخزن والزوايا الضيقة والتخلص التام من الغبار الملتصق وبقايا المواد الساقطة.",
        "goal": "تأمين أرضية مخزن نظيفة وآمنة لتفادي الحرائق أو الانزلاق ولحماية الكراتين من التلف.",
        "category": "نظافة",
        "tools_required": "مكنسة خشنة - ممسحة - جردل ومطهر مركز",
        "frequency": "أسبوعي",
        "recurrence_days": ["السبت"],
        "estimated_duration_minutes": 120,
        "scheduled_time": "11:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle57",
        "zone_id": "z_warehouse",
        "task_code": "SOP_CLE57",
        "title": "تنظيف الأجهزة بالمخزن وإزالة الأتربة",
        "description": "تنظيف وتلميع الأسطح الخارجية للأجهزة الكهربائية والمعدات والمخزونات وإزالة طبقات الأتربة عنها.",
        "goal": "المحافظة على جودة الأجهزة وحمايتها من تراكم الغبار الخشن.",
        "category": "نظافة",
        "tools_required": "فوطة مايكروفايبر جافة - ريشة غبار - بخاخ تنظيف خفيف",
        "frequency": "أسبوعي",
        "recurrence_days": ["الاثنين"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "13:00",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle58",
        "zone_id": "z_warehouse",
        "task_code": "SOP_CLE58",
        "title": "ترتيب وتنسيق الكابلات ومحتويات المخزن",
        "description": "تنظيم كراتين الكابلات والمعدات وإعادة ترتيب الأرفف الحديدية وتوفير مسارات واضحة للمرور وباب المخزن.",
        "goal": "المحافظة على كفاءة التخزين وسرعة الوصول للمواد عند الحاجة.",
        "category": "نظافة",
        "tools_required": "نظافة ترتيب عام",
        "frequency": "أسبوعي",
        "recurrence_days": ["الأربعاء"],
        "estimated_duration_minutes": 45,
        "scheduled_time": "13:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      },
      {
        "id": "t_sop_cle59",
        "zone_id": "z_warehouse",
        "task_code": "SOP_CLE59",
        "title": "تفريغ سلات المهملات وتنظيف حاوية المخزن",
        "description": "تفريغ سلات النفايات وتعقيم محيطها لضمان بقاء المخزن بيئة نظيفة وصحية.",
        "goal": "منع تراكم النفايات الكرتونية والبلاستيكية الضارة بالمخزن.",
        "category": "نظافة",
        "tools_required": "إزالة مخلفات - أكياس قمامة جديدة متينة",
        "frequency": "أسبوعي",
        "recurrence_days": ["الخميس"],
        "estimated_duration_minutes": 10,
        "scheduled_time": "14:15",
        "requires_photo_before": false,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true
      }
    ],
    "task_instances": [],
    "operational_tasks": [
      {
        "id": "op_lights",
        "zone_id": "z_reception",
        "title": "تشغيل وتعديل وحدات الإضاءة يومياً",
        "description": "تشغيل الإضاءة الهادئة حتى 12 ظهراً، الإضاءة المتوسطة من 12 ظهراً لـ 5 مساءً، والإضاءة الكاملة من 5 مساءً لـ 10 مساءً.",
        "schedule_windows": [
          { "from": "08:00", "to": "12:00", "mode": "إضاءة هادئة 💡" },
          { "from": "12:00", "to": "17:00", "mode": "إضاءة متوسطة 🔆" },
          { "from": "17:00", "to": "22:00", "mode": "إضاءة كاملة ⚡" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 001", "SWREC 002"],
        "is_active": true
      },
      {
        "id": "op_ac",
        "zone_id": "z_team_office",
        "title": "تشغيل وإطفاء التكييفات (موظفي النظافة فقط)",
        "description": "تشغيل التكييفات بدءاً من الساعة 9:00 صباحاً وإغلاقها بالكامل في تمام الساعة 10:00 مساءً من قبل موظفي النظافة فقط.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل وضبط الحرارة على 23 ❄️" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWBAS 015", "SWBAS 017"],
        "is_active": true
      },
      {
        "id": "op_sound",
        "zone_id": "z_reception",
        "title": "تشغيل الساوند سيستم يومياً",
        "description": "تشغيل نظام الصوت المركزي على الخلفية الموسيقية الهادئة من الساعة 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل مستمر هادئ 🎵" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 012"],
        "is_active": true
      },
      {
        "id": "op_fountain",
        "zone_id": "z_facades",
        "title": "تشغيل وإطفاء النوافير والشلالات",
        "description": "تشغيل النوافير والشلالات وإطفاءها لإزالة الرواسب بصفة يومية مستمرة.",
        "schedule_windows": [
          { "from": "09:00", "to": "18:00", "mode": "تشغيل مستمر Fountain ⛲" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 013"],
        "is_active": true
      },
      {
        "id": "op_screens",
        "zone_id": "z_reception",
        "title": "تشغيل شاشات العرض بالاستقبال",
        "description": "تشغيل شاشات العرض الترحيبية عند منطقة الاستقبال يومياً من 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "عرض ترحيبي ذكي 📺" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 009"],
        "is_active": true
      },
      {
        "id": "op_diffusers",
        "zone_id": "z_reception",
        "title": "تشغيل فواحات الهواء يومياً",
        "description": "تشغيل فواحات الهواء العطرية لنشر الروائح الزكية بالاستقبال من الساعة 9:00 صباحاً وحتى 9:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "21:00", "mode": "تعطير مستمر تلقائي 🌸" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 017"],
        "is_active": true
      }
    ],
    "kpi_snapshots": [
      {
        "id": "k1",
        "profile_id": "p2",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 25,
        "tasks_completed_on_time": 24,
        "tasks_late": 1,
        "tasks_reworked": 0,
        "compliance_rate": 96.0,
        "avg_execution_time_minutes": 18.5,
        "quality_score": 97,
        "supervisor_rating": 4.9
      },
      {
        "id": "k2",
        "profile_id": "p3",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 28,
        "tasks_completed_on_time": 28,
        "tasks_late": 0,
        "tasks_reworked": 1,
        "compliance_rate": 100,
        "avg_execution_time_minutes": 22.1,
        "quality_score": 94,
        "supervisor_rating": 4.7
      }
    ],
    "notifications": [],
    "device_switches": [
      // 1. لوحة الريسبشن والاستقبال (SWREC)
      { "id": "sw_rec_1", "code": "SWREC 001", "label": "إضاءات سقف مكاتب المهندسين", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_2", "code": "SWREC 002", "label": "ليد حائط حرف L", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_3", "code": "SWREC 003", "label": "ليد حائط وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_4", "code": "SWREC 004", "label": "ليد سقف وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_5", "code": "SWREC 005", "label": "ليد سقف", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_6", "code": "SWREC 006", "label": "اللمبة المدورة", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_7", "code": "SWREC 007", "label": "ليد السقف (7)", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_8", "code": "SWREC 008", "label": "ليد السقف (8)", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_9", "code": "SWREC 009", "label": "ليد أسود خلف مكاتب المهندسين", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_10", "code": "SWREC 010", "label": "ليد تجليدة مكتب وش الباب", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_11", "code": "SWREC 011", "label": "إضاءة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_12", "code": "SWREC 012", "label": "ليد خلف كنبة استقبال عملاء", "zone_id": "z_reception", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_13", "code": "SWREC 013", "label": "ليد وش النافورة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_14", "code": "SWREC 014", "label": "إضاءة خارجية", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_15", "code": "SWREC 015", "label": "سبوتات (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_16", "code": "SWREC 016", "label": "لمبة سقف (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_17", "code": "SWREC 017", "label": "ليد زرع صناعي (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_18", "code": "SWREC 018", "label": "ليد مرايات (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_19", "code": "SWREC 019", "label": "إضاءة (خارجي - 19)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_20", "code": "SWREC 020", "label": "إضاءة (خارجي - 20)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_21", "code": "SWREC 021", "label": "سبوتات سوداء شمال (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_22", "code": "SWREC 022", "label": "لمبات الكور المضيئة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_23", "code": "SWREC 023", "label": "إضاءة رقم العمارة (خارجي)", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_24", "code": "SWREC 024", "label": "سبوتات خارجية سوداء", "zone_id": "z_facades", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },

      // 2. لوحة عمال النظافة (SWMT)
      { "id": "sw_mt_1", "code": "SWMT 001", "label": "ليد سقف أعلى المفاتيح", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_2", "code": "SWMT 002", "label": "لمبات أعلى دخلة الحمام", "zone_id": "z_bathrooms", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_3", "code": "SWMT 003", "label": "ليد مكتبة الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_4", "code": "SWMT 004", "label": "ليد السقف لماتريال لاب (4)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_5", "code": "SWMT 005", "label": "ليد سقف ماتريال لاب (5)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_6", "code": "SWMT 006", "label": "ليد وسبوتات أعلى مكاتب مهندسين عند الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_7", "code": "SWMT 007", "label": "لمبات سقف مكان عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_8", "code": "SWMT 008", "label": "باقي لمبات سقف عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_9", "code": "SWMT 009", "label": "لمبات سقف السلم", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_10", "code": "SWMT 010", "label": "ليد أزرق VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_11", "code": "SWMT 011", "label": "ليد أحمر VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_12", "code": "SWMT 012", "label": "ليد التجاليد", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_13", "code": "SWMT 013", "label": "سبوت السلم الوسط", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_14", "code": "SWMT 014", "label": "ليد السلم العلوي", "zone_id": "z_facades", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_15", "code": "SWMT 015", "label": "ليد علوي مكتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_16", "code": "SWMT 016", "label": "سبوتات مكاتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_17", "code": "SWMT 017", "label": "Built-In Station سبوتات", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_18", "code": "SWMT 018", "label": "Built-In Station ليد سقف / ليد داخلي", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },

      // 3. لوحة Team Office & Technical (SWBAS)
      { "id": "sw_bas_1", "code": "SWBAS 001", "label": "ليد التجاليد خلف المكاتب", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_2", "code": "SWBAS 002", "label": "لمبات أعلى المكاتب (2)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_3", "code": "SWBAS 003", "label": "لمبات أعلى المكاتب (3)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_4", "code": "SWBAS 004", "label": "ليد التجاليد (4)", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_5", "code": "SWBAS 005", "label": "ليد سقف أصفر", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_6", "code": "SWBAS 006", "label": "ليد سقف أبيض", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_7", "code": "SWBAS 007", "label": "ليد داخل بروكيسسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_8", "code": "SWBAS 008", "label": "لوجو بروكسيسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_9", "code": "SWBAS 009", "label": "ليد أصفر خلف الجزيرة", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_10", "code": "SWBAS 010", "label": "لمبات السقف أعلى الجزيرة (10)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_11", "code": "SWBAS 011", "label": "لمبات السقف أعلى الجزيرة (11)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_12", "code": "SWBAS 012", "label": "إضاءة بروكسيسوري (1)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_13", "code": "SWBAS 013", "label": "إضاءة بروكسيسوري (2)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_14", "code": "SWBAS 014", "label": "إضاءة بروكسيسوري (3)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_15", "code": "SWBAS 015", "label": "مفتاح التكييف الرئيسي", "zone_id": "z_team_office", "panel_location": "لوحة Team Office & Technical (SWBAS)" }
    ]
  };
}
