export function getSeededDB() {
  return {
    "profiles": [
      {
        "id": "p1",
        "full_name": "أحمد المدير",
        "username": "admin",
        "role": "admin",
        "phone": "01011112222",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p2",
        "full_name": "عفاف أحمد",
        "username": "afaf",
        "role": "cleaner",
        "phone": "01234567890",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "16:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p3",
        "full_name": "رحاب محمود",
        "username": "rehab",
        "role": "cleaner",
        "phone": "01122334455",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "13:00",
        "shift_end": "21:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      },
      {
        "id": "p4",
        "full_name": "خالد المشرف",
        "username": "supervisor",
        "role": "supervisor",
        "phone": "01555666777",
        "avatar_url": "",
        "is_active": true,
        "shift_start": "08:00",
        "shift_end": "17:00",
        "work_days": [
          "السبت",
          "الأحد",
          "الاثنين",
          "الثلاثاء",
          "الأربعاء",
          "الخميس"
        ]
      }
    ],
    "locations": [
      {
        "id": "l1",
        "name": "مقر النرجس الرئيسي",
        "address": "شارع التسعين الشمالي، التجمع الخامس، القاهرة"
      }
    ],
    "zones": [
      {
        "id": "z1",
        "location_id": "l1",
        "name": "DESIGN STATION (الاستقبال والانتظار)",
        "code": "SOP_REC01",
        "floor": "الأرضي",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
        "sort_order": 1
      },
      {
        "id": "z2",
        "location_id": "l1",
        "name": "Team & Technical OFFICE (مكاتب الموظفين)",
        "code": "SOP_OFF01",
        "floor": "الأول",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=600",
        "sort_order": 2
      },
      {
        "id": "z3",
        "location_id": "l1",
        "name": "دورات المياه الثلاثة (الإدارة والعلويين)",
        "code": "SOP_WSH01",
        "floor": "الأرضي والأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
        "sort_order": 3
      },
      {
        "id": "z_material_lab",
        "location_id": "l1",
        "name": "معمل المواد (Material Lab)",
        "code": "SOP_LAB02",
        "floor": "الأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600",
        "sort_order": 4
      },
      {
        "id": "z_vr_experience",
        "location_id": "l1",
        "name": "منطقة الواقع الافتراضي (VR Experience)",
        "code": "SOP_VR01",
        "floor": "الأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=600",
        "sort_order": 5
      },
      {
        "id": "z_built_in",
        "location_id": "l1",
        "name": "محطة بيلت-إن (Built-IN Station)",
        "code": "SOP_BIN01",
        "floor": "الأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600",
        "sort_order": 6
      },
      {
        "id": "z_proxessory",
        "location_id": "l1",
        "name": "محطة بروكيسسوري (Proxessory Station)",
        "code": "SOP_PRX01",
        "floor": "الأول",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
        "sort_order": 7
      },
      {
        "id": "z_pro_home",
        "location_id": "l1",
        "name": "محطة كول سنتر (Pro Home Station)",
        "code": "SOP_PRO01",
        "floor": "الأول",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1552581234-2612b753ee93?auto=format&fit=crop&q=80&w=600",
        "sort_order": 8
      },
      {
        "id": "z_warehouse",
        "location_id": "l1",
        "name": "المخزن (Warehouse)",
        "code": "SOP_STR01",
        "floor": "الأرضي",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=600",
        "sort_order": 9
      },
      {
        "id": "z_inner_facade",
        "location_id": "l1",
        "name": "الواجهات الداخلية والزجاج والسلم",
        "code": "SOP_FAC_IN",
        "floor": "الداخلي",
        "responsible_employee_id": "p2",
        "cover_image_url": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400",
        "sort_order": 10
      },
      {
        "id": "z_outer_facade",
        "location_id": "l1",
        "name": "الواجهات الخارجية والزجاج والمدخل",
        "code": "SOP_FAC_OUT",
        "floor": "الخارجي",
        "responsible_employee_id": "p3",
        "cover_image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400",
        "sort_order": 11
      }
    ],
    "task_templates": [
      // 1. الواجهات الخارجية (z_outer_facade)
      {
        "id": "t_ext_gate_1",
        "zone_id": "z_outer_facade",
        "task_code": "SOP_EXT_01",
        "title": "البوابة الحديد والمدخل وأمام الشارع",
        "description": "كنس وتلميع البوابة الحديدية الرئيسية وتنظيف مدخل الشارع وإزالة الأتربة.",
        "goal": "المحافظة على نظافة المظهر الخارجي والمدخل الرئيسي الفاخر",
        "category": "نظافة",
        "tools_required": "مكنسة خشنة + ملمع معادن + فوطة ميكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "08:15",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_ext_gate_2",
        "zone_id": "z_outer_facade",
        "task_code": "SOP_EXT_02",
        "title": "البوابة الحديد الثانية والمدخل وأمام الشارع",
        "description": "تنظيف البوابة الحديدية الفرعية والمدخل الخارجي الموازي وإزالة القمامة والأتربة.",
        "goal": "تكامل نظافة الواجهات والبوابات الخارجية للشركة",
        "category": "نظافة",
        "tools_required": "منفضة غبار + مكنسة + مساحة مياه",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "08:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_ext_lighting",
        "zone_id": "z_outer_facade",
        "task_code": "SOP_EXT_03",
        "title": "أعمدة الإنارة والزرع (خارجي)",
        "description": "تلميع ومسح أعمدة الإنارة الخارجية وإزالة الغبار عن المزروعات والقصاري الخارجية.",
        "goal": "بريق الإضاءة الخارجية وجمال نباتات الزينة بمدخل المقر",
        "category": "نظافة",
        "tools_required": "منفضة ريش + بخاخ ملمع + فوط جافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "09:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_ext_stairs",
        "zone_id": "z_outer_facade",
        "task_code": "SOP_EXT_04",
        "title": "السلم والبوابة الزجاج الخارجي",
        "description": "مسح وتلميع السلم الرخامي الخارجي وتلميع زجاج البوابة الخارجية بشكل دائم.",
        "goal": "مدخل لامع وخالٍ تماماً من بصمات الأيدي والأتربة",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + ممسحة رخام + مطهر ديتول",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "08:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600"
      },

      // 2. الواجهات الداخلية (z_inner_facade)
      {
        "id": "t_int_mirror",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_01",
        "title": "المرايات والليد (الداخلي)",
        "description": "تلميع المرايات المعلقة وإزالة الأتربة برفق من خلف بروفايل الإضاءة الليد.",
        "goal": "لمعان برّاق للمرايا وخلوها من الأتربة التي تؤثر على جودة إضاءة الليد",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + فوطة ميكروفايبر زرقاء ناعمة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "09:15",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_int_wood",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_02",
        "title": "التجاليد الخشبية (الداخلي)",
        "description": "تلميع الحوائط والتجاليد الخشبية باستخدام ملمع الخشب لإزالة البصمات وتأمين رونقها الفاخر.",
        "goal": "المحافظة على اللون الدافئ للتجاليد الخشبية الفاخرة خالية من الغبار",
        "category": "نظافة",
        "tools_required": "بخاخ ملمع خشب + فوطة صفراء جافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "10:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_int_fountain",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_03",
        "title": "النافورة والحوائط المحيطة بها",
        "description": "مسح حوائط النافورة والتأكد من خلو مياه النافورة من الرواسب العالقة وتلميع المحيط.",
        "goal": "مظهر هادئ وصافٍ للنافورة والمنطقة المحيطة بها بالمدخل",
        "category": "نظافة",
        "tools_required": "شبكة تصفية رواسب + مطهر مياه + فوطة مسح",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "11:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_int_plants",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_04",
        "title": "تنظيف الزرع الصناعي الداخلي",
        "description": "مسح الأتربة العالقة بأوراق الزرع ونباتات الزينة الصناعية بلطف شديد.",
        "goal": "ظهور الزرع الصناعي بلونه الأخضر الزاهي الطبيعي خالياً من الأتربة",
        "category": "نظافة",
        "tools_required": "ريشة تنفيض أتربة + مناديل مبللة برفق",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "11:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_int_stairs_wood",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_05",
        "title": "تنظيف السلالم والتجاليد الخشبية والزجاج (بالتناوب)",
        "description": "مسح ومكنسة السلالم الداخلية وتلميع الدرابزين الزجاجي والخشبي بالتناوب لإزالة البصمات المستمرة.",
        "goal": "سلم داخلي فائق اللمعان والترتيب كونه حلقة الوصل بالشركة",
        "category": "نظافة",
        "tools_required": "جلانس + ملمع خشب + ممسحة ناعمة مبللة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "13:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_int_led_stairs",
        "zone_id": "z_inner_facade",
        "task_code": "SOP_INT_06",
        "title": "تنظيف الليد والتجاليد الخشبية والزجاج والسلالم",
        "description": "متابعة تلميع السلالم وتطهير الحواف ومسح خطوط إضاءة الليد الحساسة بلطف لمنع تراكم الأتربة الكثيفة.",
        "goal": "تكامل تلميع الليد والأسطح الزجاجية على السلم الداخلي",
        "category": "نظافة",
        "tools_required": "فوط ميكروفايبر جافة + ملمع زجاج + مكنسة كهربائية",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "15:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600"
      },

      // 3. DESIGN STATION (الاستقبال) (z1)
      {
        "id": "t_rec_floor",
        "zone_id": "z1",
        "task_code": "SOP_REC_01",
        "title": "الأرضيات والتجاليد والإضاءات والزجاج (الاستقبال)",
        "description": "كنس ومسح أرضية صالة الاستقبال الرخامية بالكامل وتلميع زجاج المدخل ومطهر منطقة الانتظار.",
        "goal": "أول منطقة يراها العميل، يجب أن تكون براقة بالكامل وبأجمل مظهر معقم",
        "category": "نظافة",
        "tools_required": "ممسحة أرضيات + جلانس + مطهر برائحة اللافندر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "08:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_rec_desks",
        "zone_id": "z1",
        "task_code": "SOP_REC_02",
        "title": "مكاتب المهندسين والكراسي والشاشات (الاستقبال)",
        "description": "مسح مكاتب مهندسي الاستقبال بلطف شديد، تلميع الشاشات وحوامل الكراسي ومسح الأتربة اليومية.",
        "goal": "بيئة عمل نظيفة ومحفزة للمهندسين بالاستقبال تعكس دقة الشركة",
        "category": "نظافة",
        "tools_required": "بخاخ مطهر أسطح + ملمع شاشات خاص + فوطة ميكروفايبر ناعمة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "08:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_rec_walls",
        "zone_id": "z1",
        "task_code": "SOP_REC_03",
        "title": "الحوائط والشبابيك (الاستقبال)",
        "description": "تنظيف وإزالة البقع الطفيفة عن حوائط الاستقبال وتلميع الزجاج الداخلي للشبابيك وإطارها المعدني.",
        "goal": "حوائط خالية من العيوب والشبابيك لامعة تتيح إضاءة نهارية طبيعية",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + إسفنجة ناعمة للحوائط + فوطة قطنية",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "09:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=600"
      },

      // 4. Team & Technical OFFICE (z2)
      {
        "id": "t_team_desks",
        "zone_id": "z2",
        "task_code": "SOP_OFF_01",
        "title": "تنظيف المكاتب والكراسي والشاشات (Team Office)",
        "description": "تنظيف مكاتب الموظفين بالقسم الفني ووحدات الأدراج يومياً ومسح الكابلات والشاشات بلطف بالوردية الصباحية.",
        "goal": "مكاتب نظيفة وخالية من النفايات والأتربة مع بدء ساعات العمل الرسمية",
        "category": "نظافة",
        "tools_required": "بخاخ مطهر + ملمع أسطح + أكياس نفايات سوداء",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 40,
        "scheduled_time": "08:15",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_team_paneling",
        "zone_id": "z2",
        "task_code": "SOP_OFF_02",
        "title": "تنظيف التجاليد الخشبية والأرضيات والليد والحوائط (Team Office)",
        "description": "مسح التجاليد الخشبية الفاصلة والمحيطة، كنس ومسح الأرضيات، وإزالة أتربة الليد برفق بالوردية الصباحية.",
        "goal": "تنظيف متكامل يشمل الأثاث المعماري الثابت والأرضيات بالقسم الفني",
        "category": "نظافة",
        "tools_required": "مكنسة ناعمة + ممسحة مطهرة + ملمع خشب",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 35,
        "scheduled_time": "08:50",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_team_door",
        "zone_id": "z2",
        "task_code": "SOP_OFF_03",
        "title": "تنظيف الباب والوحدات الخشب (Team Office)",
        "description": "تلميع الأبواب الخشبية للمكاتب ومقابضها الفضية وتنظيف الخزانات والوحدات الخشبية الجانبية.",
        "goal": "أبواب وخزانات معقمة وخالية تماماً من آثار الأيدي والأتربة",
        "category": "نظافة",
        "tools_required": "كحول مطهر + ملمع خشب + فوط مايكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "09:20",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1517502884422-41eaaced0168?auto=format&fit=crop&q=80&w=600"
      },

      // 5. Proxessory Station (z_proxessory)
      {
        "id": "t_prx_drawers",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_01",
        "title": "تنظيف الأدراج والضلف الداخلية والرخام (جناح الوسط)",
        "description": "فتح الأدراج والضلف الوسطى، ومسحها بالكامل من الداخل لإزالة أي بقايا، وتطهير الرخام العلوي اللامع.",
        "goal": "الحفاظ على رونق ولمعان الرخام بالوسط وخلو الوحدات الداخلية من الغبار",
        "category": "نظافة",
        "tools_required": "بخاخ مطهر رخام + ملمع خشب + فوط تنظيف قطنية",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_glass",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_02",
        "title": "تنظيف الواجهات الزجاجية والليد (Proxessory)",
        "description": "تلميع الواجهات والرفوف الزجاجية بمحطة بروكيسسوري ومسح إطارات الليد بلطف.",
        "goal": "واجهات عرض زجاجية براقة تعزز المظهر الجمالي المضيء بالليد",
        "category": "نظافة",
        "tools_required": "جلانس زجاج + فوطة زرقاء جافة ناعمة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:20",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_wood_shelves",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_03",
        "title": "تنظيف الضلف والتجاليد الخشبية (Proxessory)",
        "description": "تلميع تجاليد خشب محطة بروكيسسوري والضلف الخارجية بصفة مستمرة بملمع أثاث معتمد.",
        "goal": "حماية الهيكل الخشبي للمحطة وإبراز جمال الألوان الخشبية",
        "category": "نظافة",
        "tools_required": "بخاخ ملمع خشب + فوط قطنية صفراء",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_left_wing",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_04",
        "title": "تنظيف الضلف من الداخل (الجناح الأيسر)",
        "description": "فتح الضلف بالجانب الأيسر وإخراج المحتويات مؤقتاً ومسح الغبار وتطهير الزوايا وإعادة الترتيب.",
        "goal": "تنظيف داخلي عميق ومنظم لخزانات الجناح الأيسر",
        "category": "نظافة",
        "tools_required": "مناديل معقمة ومطهرة + فوطة جافة للتجفيف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "15:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_ext_facade",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_05",
        "title": "تنظيف الواجهات الخارجية والتجاليد الخشبية (Proxessory)",
        "description": "تلميع الهيكل الخارجي لواجهة بروكيسسوري بالكامل وتفقد خلوها من الأتربة العالقة.",
        "goal": "ضمان مظهر خارجي أنيق ومنسق يتماشى مع جودة معارض الشركة",
        "category": "نظافة",
        "tools_required": "ملمع خشب + فوط مايكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "15:20",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_mechanisms",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_06",
        "title": "تنظيف الضلف من الداخل والميكانيزمات والأدراج الداخلية",
        "description": "تنظيف مجاري ومفاصل وميكانيزمات الحركة الداخلية للضلف بلطف شديد ومسح الأدراج الداخلية المخفية.",
        "goal": "المحافظة على سلامة ميكانيكا الضلف الفاخرة وسلاسة عملها خالية من الشوائب",
        "category": "نظافة",
        "tools_required": "فرشاة صغيرة لإزالة الأتربة + مناديل كحولية جافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "15:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_prx_right_wing",
        "zone_id": "z_proxessory",
        "task_code": "SOP_PRX_07",
        "title": "تنظيف الضلف الخارجية والتجاليد الخشبية والليد (الجناح الأيمن)",
        "description": "تلميع ضلف الجناح الأيمن وإزالة الأتربة من أعلى وحدات العرض وتطهير أسطح بروفايل الليد.",
        "goal": "لمعان فائق وتناسق كامل بالجناح الأيمن لمعرض بروكيسسوري",
        "category": "نظافة",
        "tools_required": "ملمع خشب + فوط تنظيف ناعمة + سلم فحص طفيف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "16:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=600"
      },

      // 6. دورات المياة الثلاثة (z3)
      {
        "id": "t_bath_core",
        "zone_id": "z3",
        "task_code": "SOP_WSH_01",
        "title": "تنظيف الأرضيات والحوائط والبانيو والقاعدة",
        "description": "غسيل وتطهير الحمامات الثلاثة بالكامل (حمام الإدارة وحمامي الطابق الأول العلويين) بالكلور والمطهرات وتجفيفها.",
        "goal": "أعلى مستويات التعقيم وخلو الحمامات من الروائح والرواسب الكيميائية",
        "category": "نظافة",
        "tools_required": "مطهرات كلور وديتول + فرشاة حمام خشنة + ممسحة تجفيف رخام",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 35,
        "scheduled_time": "09:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": true,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_bath_amenities",
        "zone_id": "z3",
        "task_code": "SOP_WSH_02",
        "title": "تنظيف سلة المهملات والتأكد من وجود صابون ومعطر ومناديل",
        "description": "تفريغ سلات المهملات وتطهيرها داخلياً بالكامل وإعادة تزويد الحمامات بالمناديل الورقية والصابون السائل والمعطر الجوي.",
        "goal": "مخزون وافٍ وجاهزية تامة لمستلزمات الضيافة والنظافة داخل الحمامات",
        "category": "نظافة",
        "tools_required": "أكياس نفايات سوداء + سائل صابون + بخاخ معطر هواء + مناديل",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=400"
      },

      // 7. Material Lab (z_material_lab)
      {
        "id": "t_lab_wood",
        "zone_id": "z_material_lab",
        "task_code": "SOP_LAB_01",
        "title": "التجاليد الخشبية والحوائط والليد (Material Lab)",
        "description": "تلميع تجاليد خشب الماتريال لاب ومسح الأرفف وإزالة الأتربة بلطف من خلف خيوط الليد.",
        "goal": "بريق مميز لرفوف عينات التشطيبات الفاخرة وخلوها من الغبار",
        "category": "نظافة",
        "tools_required": "بخاخ ملمع خشب + فوطة مايكروفايبر صفراء",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "14:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_lab_samples_place",
        "zone_id": "z_material_lab",
        "task_code": "SOP_LAB_02",
        "title": "التأكد من وجود العينات في مكانها (Material Lab)",
        "description": "فحص وتنسيق عينات الرخام والدهانات والخرسانات والتشطيبات المعروضة للتأكد من مظهرها المرتب أمام العملاء.",
        "goal": "ترتيب وتنسيق جمالي كامل للعينات لتسهيل معاينة العملاء والمهندسين",
        "category": "تجهيز",
        "tools_required": "قفازات فحص نظيفة + كشف تنسيق العينات المعتمد",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "14:50",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_lab_drawers_inside",
        "zone_id": "z_material_lab",
        "task_code": "SOP_LAB_03",
        "title": "فتح الأدراج وتنظيفها من الداخل وتنظيف العينات الداخلية",
        "description": "سحب الأدراج التخزينية وتنظيفها من الداخل بالكامل والتأكد من ترتيب العينات داخل الفواصل الخشبية ومسح الغبار عنها.",
        "goal": "أدراج تخزينية للمواد والكتالوجات مرتبة ومنظمة بالكامل من الداخل",
        "category": "نظافة",
        "tools_required": "منفضة غبار ناعمة + بخاخ مطهر هادئ + فوطة جافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "15:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_lab_windows_ac",
        "zone_id": "z_material_lab",
        "task_code": "SOP_LAB_04",
        "title": "تنظيف الشباك والتكييف والأدراج والعينات",
        "description": "مسح وتطهير فلاتر وهيكل تكييف الماتريال لاب وتلميع الشباك الزجاجي الجانبي وإطار الشباك بالكامل.",
        "goal": "تنفس صحي وهواء نظيف داخل معمل المواد وتلميع النوافذ",
        "category": "نظافة",
        "tools_required": "فرشاة تنظيف تكييف + جلانس زجاج + سلم مخصص",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 30,
        "scheduled_time": "15:40",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=600"
      },

      // 8. VR Experience (z_vr_experience)
      {
        "id": "t_vr_led_floor",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_VR_01",
        "title": "تنظيف الليد والحوائط والأرضيات (VR Experience)",
        "description": "مسح ومكنسة السجاد الخاص بمنطقة الواقع الافتراضي بلطف، وتطهير الحوائط والليد الملون الديكوري (الأزرق والأحمر).",
        "goal": "منطقة عرض واقع افتراضي غامرة معقمة ونظيفة بالكامل للزوار والعملاء",
        "category": "نظافة",
        "tools_required": "مكنسة كهربائية + بخاخ تعقيم أثاث + فوط مايكروفايبر",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "16:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_vr_ac_unit",
        "zone_id": "z_vr_experience",
        "task_code": "SOP_VR_02",
        "title": "تنظيف الوحدة الداخلية للتكييف (VR Experience)",
        "description": "تنظيف هيكل التكييف وغسل الفلتر برفق لضمان تبريد نقي وصحي طوال فترات محاكاة الواقع الافتراضي.",
        "goal": "تنفس مثالي وتبريد مميز للمنطقة التقنية بالواقع الافتراضي",
        "category": "صيانة",
        "tools_required": "فرشاة تنظيف فلتر + مطهر تكييفات خاص + سلم",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "16:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600"
      },

      // 9. Bult-IN Station (z_built_in)
      {
        "id": "t_bin_wood_led",
        "zone_id": "z_built_in",
        "task_code": "SOP_BIN_01",
        "title": "تنظيف التجاليد الخشبية واللمبات الليد (Built-IN)",
        "description": "تلميع الأسطح الخشبية الراقية بمحطة بيلت-إن وتطهير خطوط الإضاءة الليد الديكورية بلطف.",
        "goal": "المحافظة على الطابع الفاخر لمحطة العرض Built-IN Station ومستوى إضاءتها",
        "category": "نظافة",
        "tools_required": "ملمع خشب + فوطة ميكروفايبر ناعمة وجافة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 15,
        "scheduled_time": "16:50",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_bin_appliances",
        "zone_id": "z_built_in",
        "task_code": "SOP_BIN_02",
        "title": "تنظيف الأجهزة الكهربائية والأرضيات وباب حمام السيدات",
        "description": "تطهير ومسح الأجهزة الكهربائية الواردة لغرض العرض، كنس ومسح أرضية المحطة، وتطهير باب ومقبض حمام السيدات.",
        "goal": "جاهزية كاملة ونظافة وصحة عامة للأجهزة ومحيط حمام السيدات الفاخر",
        "category": "نظافة",
        "tools_required": "كحول طبي 70% + ممسحة رخام + بخاخ مطهر أسطح",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "17:10",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p3",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600"
      },

      // 10. Pro Home Station (Call Center) (z_pro_home)
      {
        "id": "t_pro_stairs_walls",
        "zone_id": "z_pro_home",
        "task_code": "SOP_PRO_01",
        "title": "تنظيف الأرضيات والشباك الجانبي والحوائط والسلالم",
        "description": "مسح وتطهير أرضيات وسلالم محطة Pro Home، إزالة البقع عن الحوائط، وتلميع الشباك الزجاجي الجانبي.",
        "goal": "سلم وأرضيات براقة تحفز على سلاسة الحركة والعمل بمحطة Pro Home",
        "category": "نظافة",
        "tools_required": "ممسحة ناعمة + جلانس زجاج + مطهر ديتول للأرضيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "10:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_pro_devices_wood",
        "zone_id": "z_pro_home",
        "task_code": "SOP_PRO_02",
        "title": "تنظيف أجهزة الكول سنتر والتجاليد الخشبية (Pro Home)",
        "description": "تطهير سماعات الهواتف، لوحات المفاتيح وشاشات الكول سنتر بلطف شديد، ومسح وتلميع تجاليد الخشب المجاورة.",
        "goal": "حماية صحة موظفي الكول سنتر من الجراثيم والمحافظة على سلامة الوحدات التقنية والخشبيات",
        "category": "نظافة",
        "tools_required": "مناديل كحولية معقمة خاصة بالتقنيات + ملمع خشب + فوطة ناعمة",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 20,
        "scheduled_time": "10:35",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": true,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1552581234-2612b753ee93?auto=format&fit=crop&q=80&w=600"
      },

      // 11. المخزن (z_warehouse)
      {
        "id": "t_wrh_floor_cables",
        "zone_id": "z_warehouse",
        "task_code": "SOP_WRH_01",
        "title": "تنظيف الحوائط والأرضيات ومسح الكراتين والكابلات",
        "description": "كنس ومسح أرضية مخزن الكابلات والكراتين وإزالة الأتربة المتراكمة فوق الأغراض والمخزونات بلطف لمنع الغبار.",
        "goal": "المحافظة على بيئة تخزين نظيفة وآمنة خالية من الرطوبة والغبار المؤثر على المنتجات والكراتين",
        "category": "نظافة",
        "tools_required": "مكنسة خشنة + منفضة أتربة جافة + مطهر ديتول للأرضيات",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "12:00",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": true,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "t_wrh_door_boxes",
        "zone_id": "z_warehouse",
        "task_code": "SOP_WRH_02",
        "title": "تنظيف باب المخزن وترتيب الأغراض في الكراتين",
        "description": "تطهير باب ومقبض المخزن الرئيسي، ومسح الرفوف وترتيب وتنظيم الصناديق الكرتونية بشكل جمالي لتسهيل الفحص اليومي للرصيد.",
        "goal": "ترتيب تخزيني مثالي يضمن سهولة الوصول وسرعة الجرد لمستلزمات الشركة",
        "category": "تجهيز",
        "tools_required": "بخاخ مطهر أسطح + كشف جرد ورقي + منفضة غبار للرفوف",
        "frequency": "يومي",
        "recurrence_days": ["السبت", "الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
        "estimated_duration_minutes": 25,
        "scheduled_time": "12:30",
        "requires_photo_before": true,
        "requires_photo_after": true,
        "requires_supervisor_approval": true,
        "requires_gps": false,
        "requires_signature": false,
        "is_reopenable": true,
        "auto_escalate_if_late": false,
        "default_assignee_id": "p2",
        "is_active": true,
        "guide_image_url": "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&q=80&w=600"
      }
    ],
    "task_instances": [
      {
        "id": "ti_hist1",
        "template_id": "t_team_desks",
        "zone_id": "z2",
        "assigned_to": "p2",
        "assigned_by": "p1",
        "task_type": "recurring",
        "title": "تنظيف المكاتب والكراسي والشاشات (Team Office)",
        "description": "تنظيف مكاتب الموظفين بالقسم الفني ووحدات الأدراج يومياً ومسح الكابلات والشاشات بلطف بالوردية الصباحية.",
        "due_date": "2026-07-11",
        "due_time": "08:15",
        "status": "completed",
        "photo_before_url": "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400",
        "photo_after_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=400",
        "photo_after_taken_at": "2026-07-11T08:45:00Z",
        "employee_notes": "تم الانتهاء بالكامل من تنظيف وتلميع مكاتب الموظفين بالقسم الفني.",
        "supervisor_approved": true,
        "supervisor_approved_by": "p4",
        "supervisor_approved_at": "2026-07-11T08:50:00Z",
        "supervisor_notes": "عمل رائع وممتاز كالعادة ومكتمل قبل الموعد المحدد.",
        "quality_grade": "A",
        "started_at": "2026-07-11T08:15:00Z",
        "completed_at": "2026-07-11T08:45:00Z",
        "delay_minutes": 0,
        "created_at": "2026-07-11T00:00:00Z",
        "guide_image_url": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=600"
      },
      {
        "id": "ti_hist2",
        "template_id": "t_bath_core",
        "zone_id": "z3",
        "assigned_to": "p2",
        "assigned_by": "p1",
        "task_type": "recurring",
        "title": "تنظيف الأرضيات والحوائط والبانيو والقاعدة",
        "description": "غسيل وتطهير الحمامات الثلاثة بالكامل (حمام الإدارة وحمامي الطابق الأول العلويين) بالكلور والمطهرات وتجفيفها.",
        "due_date": "2026-07-11",
        "due_time": "09:00",
        "status": "completed",
        "photo_before_url": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=400",
        "photo_after_url": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=400",
        "photo_after_taken_at": "2026-07-11T09:20:00Z",
        "employee_notes": "تم التطهير الكامل بالكلور والديتول وإعادة ملء المناديل والصابون.",
        "supervisor_approved": true,
        "supervisor_approved_by": "p4",
        "supervisor_approved_at": "2026-07-11T09:25:00Z",
        "supervisor_notes": "الحمامات نظيفة جداً ومعقمة.",
        "quality_grade": "A",
        "started_at": "2026-07-11T09:00:00Z",
        "completed_at": "2026-07-11T09:20:00Z",
        "delay_minutes": 0,
        "created_at": "2026-07-11T00:00:00Z",
        "guide_image_url": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600"
      }
    ],
    "operational_tasks": [
      {
        "id": "op_lights",
        "zone_id": "z1",
        "title": "تشغيل وتعديل وحدات الإضاءة يومياً",
        "description": "تشغيل الإضاءة الهادئة حتى 12 ظهراً، الإضاءة المتوسطة من 12 ظهراً لـ 5 مساءً، والإضاءة الكاملة من 5 مساءً لـ 10 مساءً.",
        "schedule_windows": [
          { "from": "08:00", "to": "12:00", "mode": "إضاءة هادئة 💡" },
          { "from": "12:00", "to": "17:00", "mode": "إضاءة متوسطة 🔆" },
          { "from": "17:00", "to": "22:00", "mode": "إضاءة كاملة ⚡" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 001", "SWREC 002"],
        "is_active": true
      },
      {
        "id": "op_ac",
        "zone_id": "z2",
        "title": "تشغيل وإطفاء التكييفات (موظفي النظافة فقط)",
        "description": "تشغيل التكييفات بدءاً من الساعة 9:00 صباحاً وإغلاقها بالكامل في تمام الساعة 10:00 مساءً من قبل موظفي النظافة فقط.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل وضبط الحرارة على 23 ❄️" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWBAS 015"],
        "is_active": true
      },
      {
        "id": "op_sound",
        "zone_id": "z1",
        "title": "تشغيل الساوند سيستم يومياً",
        "description": "تشغيل نظام الصوت المركزي على الخلفية الموسيقية الهادئة من الساعة 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "تشغيل مستمر هادئ 🎵" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 012"],
        "is_active": true
      },
      {
        "id": "op_fountain",
        "zone_id": "z1",
        "title": "تشغيل وإطفاء النوافير والشلالات",
        "description": "تشغيل النوافير والشلالات وإطفاءها لإزالة الرواسب بصفة يومية مستمرة.",
        "schedule_windows": [
          { "from": "09:00", "to": "18:00", "mode": "تشغيل مستمر Fountain ⛲" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 013"],
        "is_active": true
      },
      {
        "id": "op_screens",
        "zone_id": "z1",
        "title": "تشغيل شاشات العرض بالاستقبال",
        "description": "تشغيل شاشات العرض الترحيبية عند منطقة الاستقبال يومياً من 9:00 صباحاً وحتى 10:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "22:00", "mode": "عرض ترحيبي ذكي 📺" }
        ],
        "responsible_employee_id": "p2",
        "switch_codes": ["SWREC 009"],
        "is_active": true
      },
      {
        "id": "op_diffusers",
        "zone_id": "z1",
        "title": "تشغيل فواحات الهواء يومياً",
        "description": "تشغيل فواحات الهواء العطرية لنشر الروائح الزكية بالاستقبال من الساعة 9:00 صباحاً وحتى 9:00 مساءً.",
        "schedule_windows": [
          { "from": "09:00", "to": "21:00", "mode": "تعطير مستمر تلقائي 🌸" }
        ],
        "responsible_employee_id": "p3",
        "switch_codes": ["SWREC 017"],
        "is_active": true
      }
    ],
    "kpi_snapshots": [
      {
        "id": "k1",
        "profile_id": "p2",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 25,
        "tasks_completed_on_time": 24,
        "tasks_late": 1,
        "tasks_reworked": 0,
        "compliance_rate": 96.0,
        "avg_execution_time_minutes": 18.5,
        "quality_score": 97,
        "supervisor_rating": 4.9
      },
      {
        "id": "k2",
        "profile_id": "p3",
        "period_type": "weekly",
        "period_start": "2026-07-05",
        "period_end": "2026-07-11",
        "tasks_assigned": 28,
        "tasks_completed_on_time": 28,
        "tasks_late": 0,
        "tasks_reworked": 1,
        "compliance_rate": 100,
        "avg_execution_time_minutes": 22.1,
        "quality_score": 94,
        "supervisor_rating": 4.7
      }
    ],
    "notifications": [
      {
        "id": "n1",
        "recipient_id": "p2",
        "type": "task_assigned",
        "title": "مهام SOP الموحدة مسندة إليك",
        "body": "تم تكليفك بجدول النظافة والتشغيل الموحد الجديد وفق لائحة الشركة.",
        "related_task_instance_id": "",
        "is_read": false,
        "created_at": "2026-07-12T01:00:00Z"
      }
    ],
    "device_switches": [
      // 1. لوحة الريسبشن والاستقبال (SWREC)
      { "id": "sw_rec_1", "code": "SWREC 001", "label": "إضاءات سقف مكاتب المهندسين", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_2", "code": "SWREC 002", "label": "ليد حائط حرف L", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_3", "code": "SWREC 003", "label": "ليد حائط وش الباب", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_4", "code": "SWREC 004", "label": "ليد سقف وش الباب", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_5", "code": "SWREC 005", "label": "ليد سقف", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_6", "code": "SWREC 006", "label": "اللمبة المدورة", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_7", "code": "SWREC 007", "label": "ليد السقف (7)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_8", "code": "SWREC 008", "label": "ليد السقف (8)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_9", "code": "SWREC 009", "label": "ليد أسود خلف مكاتب المهندسين", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_10", "code": "SWREC 010", "label": "ليد تجليدة مكتب وش الباب", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_11", "code": "SWREC 011", "label": "إضاءة (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_12", "code": "SWREC 012", "label": "ليد خلف كنبة استقبال عملاء", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_13", "code": "SWREC 013", "label": "ليد وش النافورة (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_14", "code": "SWREC 014", "label": "إضاءة خارجية", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_15", "code": "SWREC 015", "label": "سبوتات (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_16", "code": "SWREC 016", "label": "لمبة سقف (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_17", "code": "SWREC 017", "label": "ليد زرع صناعي (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_18", "code": "SWREC 018", "label": "ليد مرايات (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_19", "code": "SWREC 019", "label": "إضاءة (خارجي - 19)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_20", "code": "SWREC 020", "label": "إضاءة (خارجي - 20)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_21", "code": "SWREC 021", "label": "سبوتات سوداء شمال (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_22", "code": "SWREC 022", "label": "لمبات الكور المضيئة (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_23", "code": "SWREC 023", "label": "إضاءة رقم العمارة (خارجي)", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },
      { "id": "sw_rec_24", "code": "SWREC 024", "label": "سبوتات خارجية سوداء", "zone_id": "z1", "panel_location": "لوحة الريسبشن والاستقبال (SWREC)" },

      // 2. لوحة عمال النظافة (SWMT)
      { "id": "sw_mt_1", "code": "SWMT 001", "label": "ليد سقف أعلى المفاتيح", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_2", "code": "SWMT 002", "label": "لمبات أعلى دخلة الحمام", "zone_id": "z3", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_3", "code": "SWMT 003", "label": "ليد مكتبة الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_4", "code": "SWMT 004", "label": "ليد السقف لماتريال لاب (4)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_5", "code": "SWMT 005", "label": "ليد سقف ماتريال لاب (5)", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_6", "code": "SWMT 006", "label": "ليد وسبوتات أعلى مكاتب مهندسين عند الماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_7", "code": "SWMT 007", "label": "لمبات سقف مكان عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_8", "code": "SWMT 008", "label": "باقي لمبات سقف عمال النظافة", "zone_id": "z_warehouse", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_9", "code": "SWMT 009", "label": "لمبات سقف السلم", "zone_id": "z_inner_facade", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_10", "code": "SWMT 010", "label": "ليد أزرق VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_11", "code": "SWMT 011", "label": "ليد أحمر VR", "zone_id": "z_vr_experience", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_12", "code": "SWMT 012", "label": "ليد التجاليد", "zone_id": "z_inner_facade", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_13", "code": "SWMT 013", "label": "سبوت السلم الوسط", "zone_id": "z_inner_facade", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_14", "code": "SWMT 014", "label": "ليد السلم العلوي", "zone_id": "z_inner_facade", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_15", "code": "SWMT 015", "label": "ليد علوي مكتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_16", "code": "SWMT 016", "label": "سبوتات مكاتب مهندسين ماتريال لاب", "zone_id": "z_material_lab", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_17", "code": "SWMT 017", "label": "Built-In Station سبوتات", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },
      { "id": "sw_mt_18", "code": "SWMT 018", "label": "Built-In Station ليد سقف / ليد داخلي", "zone_id": "z_built_in", "panel_location": "لوحة عمال النظافة (SWMT)" },

      // 3. لوحة Team Office & Technical (SWBAS)
      { "id": "sw_bas_1", "code": "SWBAS 001", "label": "ليد التجاليد خلف المكاتب", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_2", "code": "SWBAS 002", "label": "لمبات أعلى المكاتب (2)", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_3", "code": "SWBAS 003", "label": "لمبات أعلى المكاتب (3)", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_4", "code": "SWBAS 004", "label": "ليد التجاليد (4)", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_5", "code": "SWBAS 005", "label": "ليد سقف أصفر", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_6", "code": "SWBAS 006", "label": "ليد سقف أبيض", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_7", "code": "SWBAS 007", "label": "ليد داخل بروكيسسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_8", "code": "SWBAS 008", "label": "لوجو بروكسيسوري", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_9", "code": "SWBAS 009", "label": "ليد أصفر خلف الجزيرة", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_10", "code": "SWBAS 010", "label": "لمبات السقف أعلى الجزيرة (10)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_11", "code": "SWBAS 011", "label": "لمبات السقف أعلى الجزيرة (11)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_12", "code": "SWBAS 012", "label": "إضاءة بروكسيسوري (1)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_13", "code": "SWBAS 013", "label": "إضاءة بروكسيسوري (2)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_14", "code": "SWBAS 014", "label": "إضاءة بروكسيسوري (3)", "zone_id": "z_proxessory", "panel_location": "لوحة Team Office & Technical (SWBAS)" },
      { "id": "sw_bas_15", "code": "SWBAS 015", "label": "مفتاح التكييف الرئيسي", "zone_id": "z2", "panel_location": "لوحة Team Office & Technical (SWBAS)" }
    ]
  };
}
